import { z } from 'zod';

// Zod schema for theme validation
// Derived CSS var: --border (computed from isDark)
export const ThemeColorsSchema = z.object({
    background: z.string(),       // Main page background
    cardBg: z.string(),           // Card/panel backgrounds (semi-transparent)
    textPrimary: z.string(),      // Primary text color
    textSecondary: z.string(),    // Muted/secondary text color
    accent: z.string(),           // Links, highlights, interactive elements
    secondary: z.string(),        // Secondary/hover states
    titleColor: z.string(),       // Logo/title color (solid or gradient)
    specialColor: z.string(),     // Special highlights like powder days (solid or gradient)
});

export const ThemeSchema = z.object({
    id: z.string(),
    name: z.string(),
    isDark: z.boolean(),
    colors: ThemeColorsSchema,
});

export type ThemeColors = z.infer<typeof ThemeColorsSchema>;
export type Theme = z.infer<typeof ThemeSchema>;

// Theme definitions
export const themes: Theme[] = [
    {
        id: 'light',
        name: 'Light',
        isDark: false,
        colors: {
            background: '#ffffffff',
            cardBg: 'rgba(255, 255, 255, 0.8)',
            textPrimary: '#1d1d1f',
            textSecondary: '#6d6d75ff',
            accent: '#0071e3',
            secondary: '#f7f7f7ff',
            titleColor: 'linear-gradient(209deg, #ea6044 39%, #dc5083 50%, #9a6df7 67%, #3f8def 81%)',
            specialColor: 'linear-gradient(90deg, #0071e3, #af52de)',
        },
    },
    {
        id: 'dark',
        name: 'Dark',
        isDark: true,
        colors: {
            background: '#000000ff',
            cardBg: 'rgba(28, 28, 30, 0.8)',
            textPrimary: '#f5f5f7',
            textSecondary: '#a1a1a6',
            accent: '#0a84ff',
            secondary: '#2c2c2e',
            titleColor: 'linear-gradient(209deg, #ea6044 39%, #dc5083 50%, #9a6df7 67%, #3f8def 81%)',
            specialColor: 'linear-gradient(90deg, #FF375F, #FF453A, #FF9F0A, #FFD60A, #30D158, #66D4CF, #40C8E0, #0A84FF, #5E5CE6, #BF5AF2, #FF375F)',
        },
    },
    {
        id: 'serika-dark',
        name: 'Serika Dark',
        isDark: true,
        colors: {
            background: '#323437',
            cardBg: 'rgba(44, 46, 49, 0.8)',
            textPrimary: '#d1d0c5',
            textSecondary: '#646669',
            accent: '#e2b714',
            secondary: '#3c3e41',
            titleColor: '#e2b714',
            specialColor: '#e2b714',
        },
    },
    {
        id: 'nord',
        name: 'Nord',
        isDark: true,
        colors: {
            background: '#2e3440',
            cardBg: 'rgba(59, 66, 82, 0.8)',
            textPrimary: '#eceff4',
            textSecondary: '#d8dee9',
            accent: '#88c0d0',
            secondary: '#4c566a',
            titleColor: '#88c0d0',
            specialColor: '#88c0d0',
        },
    },
    {
        id: 'monokai',
        name: 'Monokai',
        isDark: true,
        colors: {
            background: '#272822',
            cardBg: 'rgba(62, 61, 50, 0.8)',
            textPrimary: '#f8f8f2',
            textSecondary: '#75715e',
            accent: '#a6e22e',
            secondary: '#4e4d42',
            titleColor: '#a6e22e',
            specialColor: '#a6e22e',
        },
    },
    {
        id: 'dracula',
        name: 'Dracula',
        isDark: true,
        colors: {
            background: '#282a36',
            cardBg: 'rgba(68, 71, 90, 0.8)',
            textPrimary: '#f8f8f2',
            textSecondary: '#6272a4',
            accent: '#bd93f9',
            secondary: '#545770',
            titleColor: '#bd93f9',
            specialColor: '#bd93f9',
        },
    },
    {
        id: 'macroblank',
        name: 'Macroblank',
        isDark: false,
        colors: {
            background: '#b2d2c8',
            cardBg: '#b2d2c8',
            textPrimary: '#414847',
            textSecondary: '#717977',
            accent: '#c13117',
            secondary: 'rgba(197, 221, 210, 1)',
            titleColor: '#c13117',
            specialColor: 'linear-gradient(90deg, #c13117, #61706b)',
        },
    },
    {
        id: 'matcha-mocha',
        name: 'Matcha Mocha',
        isDark: false,
        colors: {
            background: '#73655d',
            cardBg: '#73655d',
            textPrimary: '#f2ded0',
            textSecondary: '#bbbf7d',
            accent: '#d5eaa9',
            secondary: '#867b73ff',
            titleColor: '#f2ded0',
            specialColor: '#d0ff009a',
        },
    },
    {
        id: 'rose-gold',
        name: 'Rose Gold',
        isDark: false,
        colors: {
            background: '#ce9a95',
            cardBg: '#ce9a95',
            textPrimary: '#ffe4e4ff',
            textSecondary: '#5c4749ff',
            accent: '#f8c8c0ff',
            secondary: '#b98379',
            titleColor: '#ffd6d0ff',
            specialColor: '#7e2a33',
        },
    },
    {
        id: 'bushido',
        name: 'Bushido',
        isDark: true,
        colors: {
            background: '#242933',
            cardBg: '#242933',
            textPrimary: '#f1ebe4',
            textSecondary: '#596172',
            accent: '#ec4c56',
            secondary: '#1c222d',
            titleColor: '#ec4c56',
            specialColor: '#ec4c56',
        },
    },
    // Adapted from Monkeytype's community themes (github.com/monkeytypegame/monkeytype, GPL-3.0,
    // as of commit 476fe5e0). Only their names and colour values are used, converted by rule:
    //   background, cardBg <- bg      secondary <- subAlt
    //   textPrimary <- text           textSecondary <- sub
    //   accent, titleColor <- main
    //   specialColor <- gradient from main to caret, or to text, or to sub: the first that
    //                   differs visibly from main
    //   isDark <- white contrasts better than black on bg
    // text is then lightened or darkened (hue kept) to 4.5:1, and sub, main and caret to 3:1,
    // against both bg and subAlt. Skipped because the hand-tuned versions above stay:
    // serika_dark, nord, monokai, dracula, macroblank, bushido. Renamed to avoid clashing
    // with the themes above: dark -> Graphite, matcha_moccha -> Matcha Brownie.
    {
        id: '8008',
        name: '8008',
        isDark: true,
        colors: {
            background: '#333a45',
            cardBg: '#333a45',
            textPrimary: '#e9ecf0',
            textSecondary: '#939eae',
            accent: '#f44c7f',
            secondary: '#2e343d',
            titleColor: '#f44c7f',
            specialColor: 'linear-gradient(90deg, #f44c7f, #e9ecf0)',
        },
    },
    {
        id: '80s-after-dark',
        name: '80s After Dark',
        isDark: true,
        colors: {
            background: '#1b1d36',
            cardBg: '#1b1d36',
            textPrimary: '#e1e7ec',
            textSecondary: '#99d6ea',
            accent: '#fca6d1',
            secondary: '#17182c',
            titleColor: '#fca6d1',
            specialColor: 'linear-gradient(90deg, #fca6d1, #99d6ea)',
        },
    },
    {
        id: '9009',
        name: '9009',
        isDark: false,
        colors: {
            background: '#eeebe2',
            cardBg: '#eeebe2',
            textPrimary: '#080909',
            textSecondary: '#797461',
            accent: '#080909',
            secondary: '#d3cfc1',
            titleColor: '#080909',
            specialColor: 'linear-gradient(90deg, #080909, #597c59)',
        },
    },
    {
        id: 'aether',
        name: 'Aether',
        isDark: true,
        colors: {
            background: '#101820',
            cardBg: '#101820',
            textPrimary: '#eedaea',
            textSecondary: '#cf6bdd',
            accent: '#eedaea',
            secondary: '#292136',
            titleColor: '#eedaea',
            specialColor: 'linear-gradient(90deg, #eedaea, #cf6bdd)',
        },
    },
    {
        id: 'alduin',
        name: 'Alduin',
        isDark: true,
        colors: {
            background: '#1c1c1c',
            cardBg: '#1c1c1c',
            textPrimary: '#f5f3ed',
            textSecondary: '#6d6d6d',
            accent: '#dfd7af',
            secondary: '#242424',
            titleColor: '#dfd7af',
            specialColor: 'linear-gradient(90deg, #dfd7af, #f5f3ed)',
        },
    },
    {
        id: 'alpine',
        name: 'Alpine',
        isDark: true,
        colors: {
            background: '#6c687f',
            cardBg: '#6c687f',
            textPrimary: '#ffffff',
            textSecondary: '#d3d0e0',
            accent: '#ffffff',
            secondary: '#77738c',
            titleColor: '#ffffff',
            specialColor: 'linear-gradient(90deg, #ffffff, #222028)',
        },
    },
    {
        id: 'anti-hero',
        name: 'Anti Hero',
        isDark: true,
        colors: {
            background: '#00002e',
            cardBg: '#00002e',
            textPrimary: '#f1deef',
            textSecondary: '#ff3d8b',
            accent: '#ffadad',
            secondary: '#060548',
            titleColor: '#ffadad',
            specialColor: 'linear-gradient(90deg, #ffadad, #ffffff)',
        },
    },
    {
        id: 'arch',
        name: 'Arch',
        isDark: true,
        colors: {
            background: '#0c0d11',
            cardBg: '#0c0d11',
            textPrimary: '#f6f5f5',
            textSecondary: '#5f638a',
            accent: '#7ebab5',
            secondary: '#171a25',
            titleColor: '#7ebab5',
            specialColor: 'linear-gradient(90deg, #7ebab5, #f6f5f5)',
        },
    },
    {
        id: 'aurora',
        name: 'Aurora',
        isDark: true,
        colors: {
            background: '#011926',
            cardBg: '#011926',
            textPrimary: '#ffffff',
            textSecondary: '#2a6c7b',
            accent: '#00e980',
            secondary: '#000c13',
            titleColor: '#00e980',
            specialColor: 'linear-gradient(90deg, #00e980, #ffffff)',
        },
    },
    {
        id: 'beach',
        name: 'Beach',
        isDark: false,
        colors: {
            background: '#ffeead',
            cardBg: '#ffeead',
            textPrimary: '#4f685b',
            textSecondary: '#a97400',
            accent: '#428c6a',
            secondary: '#f7dc8f',
            titleColor: '#428c6a',
            specialColor: 'linear-gradient(90deg, #428c6a, #a97400)',
        },
    },
    {
        id: 'bento',
        name: 'Bento',
        isDark: true,
        colors: {
            background: '#2d394d',
            cardBg: '#2d394d',
            textPrimary: '#fffaf8',
            textSecondary: '#5588a2',
            accent: '#ff7a90',
            secondary: '#263041',
            titleColor: '#ff7a90',
            specialColor: 'linear-gradient(90deg, #ff7a90, #fffaf8)',
        },
    },
    {
        id: 'bingsu',
        name: 'Bingsu',
        isDark: false,
        colors: {
            background: '#b8a7aa',
            cardBg: '#b8a7aa',
            textPrimary: '#3e313b',
            textSecondary: '#48373d',
            accent: '#624852',
            secondary: '#ab989e',
            titleColor: '#624852',
            specialColor: 'linear-gradient(90deg, #624852, #3e313b)',
        },
    },
    {
        id: 'bliss',
        name: 'Bliss',
        isDark: true,
        colors: {
            background: '#262727',
            cardBg: '#262727',
            textPrimary: '#ffffff',
            textSecondary: '#897774',
            accent: '#f0d3c9',
            secondary: '#343231',
            titleColor: '#f0d3c9',
            specialColor: 'linear-gradient(90deg, #f0d3c9, #ffffff)',
        },
    },
    {
        id: 'blue-dolphin',
        name: 'Blue Dolphin',
        isDark: true,
        colors: {
            background: '#003950',
            cardBg: '#003950',
            textPrimary: '#82eaff',
            textSecondary: '#00e4ff',
            accent: '#ffcefb',
            secondary: '#014961',
            titleColor: '#ffcefb',
            specialColor: 'linear-gradient(90deg, #ffcefb, #00bcd4)',
        },
    },
    {
        id: 'blueberry-dark',
        name: 'Blueberry Dark',
        isDark: true,
        colors: {
            background: '#212b42',
            cardBg: '#212b42',
            textPrimary: '#91b4d5',
            textSecondary: '#5c7da5',
            accent: '#add7ff',
            secondary: '#1b2334',
            titleColor: '#add7ff',
            specialColor: 'linear-gradient(90deg, #add7ff, #c23da3)',
        },
    },
    {
        id: 'blueberry-light',
        name: 'Blueberry Light',
        isDark: false,
        colors: {
            background: '#dae0f5',
            cardBg: '#dae0f5',
            textPrimary: '#455666',
            textSecondary: '#587094',
            accent: '#506477',
            secondary: '#c1c7df',
            titleColor: '#506477',
            specialColor: 'linear-gradient(90deg, #506477, #d2245c)',
        },
    },
    {
        id: 'botanical',
        name: 'Botanical',
        isDark: false,
        colors: {
            background: '#7b9c98',
            cardBg: '#7b9c98',
            textPrimary: '#18262b',
            textSecondary: '#384241',
            accent: '#2b434b',
            secondary: '#72908d',
            titleColor: '#2b434b',
            specialColor: 'linear-gradient(90deg, #2b434b, #18262b)',
        },
    },
    {
        id: 'bouquet',
        name: 'Bouquet',
        isDark: true,
        colors: {
            background: '#173f35',
            cardBg: '#173f35',
            textPrimary: '#e9e0d2',
            textSecondary: '#48a18b',
            accent: '#eaa09c',
            secondary: '#1f4e43',
            titleColor: '#eaa09c',
            specialColor: 'linear-gradient(90deg, #eaa09c, #e9e0d2)',
        },
    },
    {
        id: 'breeze',
        name: 'Breeze',
        isDark: false,
        colors: {
            background: '#e8d5c4',
            cardBg: '#e8d5c4',
            textPrimary: '#1b4c5e',
            textSecondary: '#3283a0',
            accent: '#7d67a9',
            secondary: '#f6e6da',
            titleColor: '#7d67a9',
            specialColor: 'linear-gradient(90deg, #7d67a9, #1b4c5e)',
        },
    },
    {
        id: 'cafe',
        name: 'Cafe',
        isDark: false,
        colors: {
            background: '#ceb18d',
            cardBg: '#ceb18d',
            textPrimary: '#14120f',
            textSecondary: '#585553',
            accent: '#14120f',
            secondary: '#bba180',
            titleColor: '#14120f',
            specialColor: 'linear-gradient(90deg, #14120f, #585553)',
        },
    },
    {
        id: 'camping',
        name: 'Camping',
        isDark: false,
        colors: {
            background: '#faf1e4',
            cardBg: '#faf1e4',
            textPrimary: '#3c403b',
            textSecondary: '#8c7b64',
            accent: '#5f8854',
            secondary: '#e7dccb',
            titleColor: '#5f8854',
            specialColor: 'linear-gradient(90deg, #5f8854, #3c403b)',
        },
    },
    {
        id: 'carbon',
        name: 'Carbon',
        isDark: true,
        colors: {
            background: '#313131',
            cardBg: '#313131',
            textPrimary: '#f5e6c8',
            textSecondary: '#7a7a7a',
            accent: '#f66e0d',
            secondary: '#2b2b2b',
            titleColor: '#f66e0d',
            specialColor: 'linear-gradient(90deg, #f66e0d, #f5e6c8)',
        },
    },
    {
        id: 'catppuccin',
        name: 'Catppuccin',
        isDark: true,
        colors: {
            background: '#1e1e2e',
            cardBg: '#1e1e2e',
            textPrimary: '#cdd6f4',
            textSecondary: '#7f849c',
            accent: '#cba6f7',
            secondary: '#181825',
            titleColor: '#cba6f7',
            specialColor: 'linear-gradient(90deg, #cba6f7, #f2cdcd)',
        },
    },
    {
        id: 'chaos-theory',
        name: 'Chaos Theory',
        isDark: true,
        colors: {
            background: '#141221',
            cardBg: '#141221',
            textPrimary: '#dde5ed',
            textSecondary: '#676e8a',
            accent: '#fd77d7',
            secondary: '#1e1d2f',
            titleColor: '#fd77d7',
            specialColor: 'linear-gradient(90deg, #fd77d7, #dde5ed)',
        },
    },
    {
        id: 'cheesecake',
        name: 'Cheesecake',
        isDark: false,
        colors: {
            background: '#fdf0d5',
            cardBg: '#fdf0d5',
            textPrimary: '#3a3335',
            textSecondary: '#d91c81',
            accent: '#8e2949',
            secondary: '#f3e2bf',
            titleColor: '#8e2949',
            specialColor: 'linear-gradient(90deg, #8e2949, #3a3335)',
        },
    },
    {
        id: 'cherry-blossom',
        name: 'Cherry Blossom',
        isDark: true,
        colors: {
            background: '#323437',
            cardBg: '#323437',
            textPrimary: '#d1d0c5',
            textSecondary: '#787d82',
            accent: '#d65ccc',
            secondary: '#2d2f31',
            titleColor: '#d65ccc',
            specialColor: 'linear-gradient(90deg, #d65ccc, #ffffff)',
        },
    },
    {
        id: 'comfy',
        name: 'Comfy',
        isDark: true,
        colors: {
            background: '#4a5b6e',
            cardBg: '#4a5b6e',
            textPrimary: '#f5efee',
            textSecondary: '#9ec1cc',
            accent: '#f8cdc6',
            secondary: '#425366',
            titleColor: '#f8cdc6',
            specialColor: 'linear-gradient(90deg, #f8cdc6, #9ec1cc)',
        },
    },
    {
        id: 'copper',
        name: 'Copper',
        isDark: true,
        colors: {
            background: '#442f29',
            cardBg: '#442f29',
            textPrimary: '#e7e0de',
            textSecondary: '#7ebab5',
            accent: '#b97460',
            secondary: '#50362e',
            titleColor: '#b97460',
            specialColor: 'linear-gradient(90deg, #b97460, #e7e0de)',
        },
    },
    {
        id: 'creamsicle',
        name: 'Creamsicle',
        isDark: false,
        colors: {
            background: '#ff9869',
            cardBg: '#ff9869',
            textPrimary: '#40401c',
            textSecondary: '#a03300',
            accent: '#5b5b27',
            secondary: '#fe8954',
            titleColor: '#5b5b27',
            specialColor: 'linear-gradient(90deg, #5b5b27, #a03300)',
        },
    },
    {
        id: 'cy-red',
        name: 'Cy Red',
        isDark: true,
        colors: {
            background: '#6e2626',
            cardBg: '#6e2626',
            textPrimary: '#ffaaaa',
            textSecondary: '#ff6060',
            accent: '#e65959',
            secondary: '#3f1616',
            titleColor: '#e65959',
            specialColor: 'linear-gradient(90deg, #e65959, #ffaaaa)',
        },
    },
    {
        id: 'cyberspace',
        name: 'Cyberspace',
        isDark: true,
        colors: {
            background: '#181c18',
            cardBg: '#181c18',
            textPrimary: '#c2fbe1',
            textSecondary: '#9578d3',
            accent: '#00ce7c',
            secondary: '#131613',
            titleColor: '#00ce7c',
            specialColor: 'linear-gradient(90deg, #00ce7c, #c2fbe1)',
        },
    },
    {
        id: 'dark-magic-girl',
        name: 'Dark Magic Girl',
        isDark: true,
        colors: {
            background: '#091f2c',
            cardBg: '#091f2c',
            textPrimary: '#a288d9',
            textSecondary: '#93e8d3',
            accent: '#f5b1cc',
            secondary: '#071823',
            titleColor: '#f5b1cc',
            specialColor: 'linear-gradient(90deg, #f5b1cc, #a288d9)',
        },
    },
    {
        id: 'dark-note',
        name: 'Dark Note',
        isDark: true,
        colors: {
            background: '#1f1f1f',
            cardBg: '#1f1f1f',
            textPrimary: '#d2dff4',
            textSecondary: '#768f95',
            accent: '#f2c17b',
            secondary: '#141414',
            titleColor: '#f2c17b',
            specialColor: 'linear-gradient(90deg, #f2c17b, #e3dce0)',
        },
    },
    {
        id: 'darling',
        name: 'Darling',
        isDark: false,
        colors: {
            background: '#fec8cd',
            cardBg: '#fec8cd',
            textPrimary: '#545454',
            textSecondary: '#a30000',
            accent: '#6e6e6e',
            secondary: '#f2babd',
            titleColor: '#6e6e6e',
            specialColor: 'linear-gradient(90deg, #6e6e6e, #a30000)',
        },
    },
    {
        id: 'deku',
        name: 'Deku',
        isDark: false,
        colors: {
            background: '#058b8c',
            cardBg: '#058b8c',
            textPrimary: '#000000',
            textSecondary: '#132b2e',
            accent: '#4a1614',
            secondary: '#0e7d7e',
            titleColor: '#4a1614',
            specialColor: 'linear-gradient(90deg, #4a1614, #000000)',
        },
    },
    {
        id: 'desert-oasis',
        name: 'Desert Oasis',
        isDark: false,
        colors: {
            background: '#fff2d5',
            cardBg: '#fff2d5',
            textPrimary: '#332800',
            textSecondary: '#0061fe',
            accent: '#a17901',
            secondary: '#eddebc',
            titleColor: '#a17901',
            specialColor: 'linear-gradient(90deg, #a17901, #2479fe)',
        },
    },
    {
        id: 'dev',
        name: 'Dev',
        isDark: true,
        colors: {
            background: '#1b2028',
            cardBg: '#1b2028',
            textPrimary: '#ccccb5',
            textSecondary: '#596a8b',
            accent: '#23a9d5',
            secondary: '#151a21',
            titleColor: '#23a9d5',
            specialColor: 'linear-gradient(90deg, #23a9d5, #596a8b)',
        },
    },
    {
        id: 'diner',
        name: 'Diner',
        isDark: true,
        colors: {
            background: '#537997',
            cardBg: '#537997',
            textPrimary: '#fdfcfb',
            textSecondary: '#192230',
            accent: '#dcd1a0',
            secondary: '#4d6f8b',
            titleColor: '#dcd1a0',
            specialColor: 'linear-gradient(90deg, #dcd1a0, #361a16)',
        },
    },
    {
        id: 'dino',
        name: 'Dino',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#1d221f',
            textSecondary: '#898989',
            accent: '#229d4b',
            secondary: '#cafad8',
            titleColor: '#229d4b',
            specialColor: 'linear-gradient(90deg, #229d4b, #1d221f)',
        },
    },
    {
        id: 'discord',
        name: 'Discord',
        isDark: true,
        colors: {
            background: '#313338',
            cardBg: '#313338',
            textPrimary: '#dcdee3',
            textSecondary: '#787b88',
            accent: '#646feb',
            secondary: '#2b2d31',
            titleColor: '#646feb',
            specialColor: 'linear-gradient(90deg, #646feb, #dcdee3)',
        },
    },
    {
        id: 'dmg',
        name: 'DMG',
        isDark: false,
        colors: {
            background: '#dadbdc',
            cardBg: '#dadbdc',
            textPrimary: '#414141',
            textSecondary: '#3846b1',
            accent: '#ae185e',
            secondary: '#bec1d2',
            titleColor: '#ae185e',
            specialColor: 'linear-gradient(90deg, #ae185e, #384693)',
        },
    },
    {
        id: 'dollar',
        name: 'Dollar',
        isDark: false,
        colors: {
            background: '#e4e4d4',
            cardBg: '#e4e4d4',
            textPrimary: '#555956',
            textSecondary: '#6b7850',
            accent: '#607960',
            secondary: '#cbd0bf',
            titleColor: '#607960',
            specialColor: 'linear-gradient(90deg, #607960, #424643)',
        },
    },
    {
        id: 'dots',
        name: 'Dots',
        isDark: true,
        colors: {
            background: '#121520',
            cardBg: '#121520',
            textPrimary: '#ffffff',
            textSecondary: '#676e8a',
            accent: '#ffffff',
            secondary: '#1b1e2c',
            titleColor: '#ffffff',
            specialColor: 'linear-gradient(90deg, #ffffff, #676e8a)',
        },
    },
    {
        id: 'drowning',
        name: 'Drowning',
        isDark: true,
        colors: {
            background: '#191826',
            cardBg: '#191826',
            textPrimary: '#9393a7',
            textSecondary: '#536b91',
            accent: '#4a6fb5',
            secondary: '#1e1f2f',
            titleColor: '#4a6fb5',
            specialColor: 'linear-gradient(90deg, #4a6fb5, #9393a7)',
        },
    },
    {
        id: 'dualshot',
        name: 'Dualshot',
        isDark: true,
        colors: {
            background: '#737373',
            cardBg: '#737373',
            textPrimary: '#f9f9f9',
            textSecondary: '#cecece',
            accent: '#181818',
            secondary: '#646464',
            titleColor: '#181818',
            specialColor: 'linear-gradient(90deg, #181818, #f9f9f9)',
        },
    },
    {
        id: 'earthsong',
        name: 'Earthsong',
        isDark: true,
        colors: {
            background: '#292521',
            cardBg: '#292521',
            textPrimary: '#e6c7a8',
            textSecondary: '#f5ae2d',
            accent: '#509452',
            secondary: '#1d1b18',
            titleColor: '#509452',
            specialColor: 'linear-gradient(90deg, #509452, #1298ba)',
        },
    },
    {
        id: 'everblush',
        name: 'Everblush',
        isDark: true,
        colors: {
            background: '#141b1e',
            cardBg: '#141b1e',
            textPrimary: '#dadada',
            textSecondary: '#838887',
            accent: '#8ccf7e',
            secondary: '#232a2d',
            titleColor: '#8ccf7e',
            specialColor: 'linear-gradient(90deg, #8ccf7e, #6cbfbf)',
        },
    },
    {
        id: 'evil-eye',
        name: 'Evil Eye',
        isDark: false,
        colors: {
            background: '#0084c2',
            cardBg: '#0084c2',
            textPrimary: '#000000',
            textSecondary: '#012d51',
            accent: '#f7f2ea',
            secondary: '#0c79be',
            titleColor: '#f7f2ea',
            specialColor: 'linear-gradient(90deg, #f7f2ea, #000000)',
        },
    },
    {
        id: 'ez-mode',
        name: 'EZ Mode',
        isDark: true,
        colors: {
            background: '#0068c6',
            cardBg: '#0068c6',
            textPrimary: '#ffffff',
            textSecondary: '#88c5fb',
            accent: '#fca2e6',
            secondary: '#005bac',
            titleColor: '#fca2e6',
            specialColor: 'linear-gradient(90deg, #fca2e6, #4ddb47)',
        },
    },
    {
        id: 'fire',
        name: 'Fire',
        isDark: true,
        colors: {
            background: '#0f0000',
            cardBg: '#0f0000',
            textPrimary: '#ffffff',
            textSecondary: '#944a4a',
            accent: '#c01414',
            secondary: '#200a0a',
            titleColor: '#c01414',
            specialColor: 'linear-gradient(90deg, #c01414, #ffffff)',
        },
    },
    {
        id: 'fledgling',
        name: 'Fledgling',
        isDark: true,
        colors: {
            background: '#3b363f',
            cardBg: '#3b363f',
            textPrimary: '#e6d5d3',
            textSecondary: '#aa7084',
            accent: '#fc6e83',
            secondary: '#332e38',
            titleColor: '#fc6e83',
            specialColor: 'linear-gradient(90deg, #fc6e83, #818181)',
        },
    },
    {
        id: 'fleuriste',
        name: 'Fleuriste',
        isDark: false,
        colors: {
            background: '#c6b294',
            cardBg: '#c6b294',
            textPrimary: '#091914',
            textSecondary: '#64374d',
            accent: '#405a52',
            secondary: '#b4a389',
            titleColor: '#405a52',
            specialColor: 'linear-gradient(90deg, #405a52, #091914)',
        },
    },
    {
        id: 'floret',
        name: 'Floret',
        isDark: true,
        colors: {
            background: '#00272c',
            cardBg: '#00272c',
            textPrimary: '#e5e5e5',
            textSecondary: '#779097',
            accent: '#ffdd6d',
            secondary: '#173033',
            titleColor: '#ffdd6d',
            specialColor: 'linear-gradient(90deg, #ffdd6d, #c3bd40)',
        },
    },
    {
        id: 'froyo',
        name: 'Froyo',
        isDark: false,
        colors: {
            background: '#e1dacb',
            cardBg: '#e1dacb',
            textPrimary: '#575858',
            textSecondary: '#83713f',
            accent: '#727373',
            secondary: '#d3cdc1',
            titleColor: '#727373',
            specialColor: 'linear-gradient(90deg, #727373, #83713f)',
        },
    },
    {
        id: 'frozen-llama',
        name: 'Frozen Llama',
        isDark: false,
        colors: {
            background: '#9bf2ea',
            cardBg: '#9bf2ea',
            textPrimary: '#5d5d5d',
            textSecondary: '#8e52fc',
            accent: '#6d44a6',
            secondary: '#7fe7dd',
            titleColor: '#6d44a6',
            specialColor: 'linear-gradient(90deg, #6d44a6, #787878)',
        },
    },
    {
        id: 'fruit-chew',
        name: 'Fruit Chew',
        isDark: false,
        colors: {
            background: '#d6d3d6',
            cardBg: '#d6d3d6',
            textPrimary: '#282528',
            textSecondary: '#806081',
            accent: '#5c1e5f',
            secondary: '#cabfca',
            titleColor: '#5c1e5f',
            specialColor: 'linear-gradient(90deg, #5c1e5f, #b92221)',
        },
    },
    {
        id: 'fundamentals',
        name: 'Fundamentals',
        isDark: true,
        colors: {
            background: '#727474',
            cardBg: '#727474',
            textPrimary: '#fafafa',
            textSecondary: '#d3cec8',
            accent: '#c2d3c3',
            secondary: '#666868',
            titleColor: '#c2d3c3',
            specialColor: 'linear-gradient(90deg, #c2d3c3, #082027)',
        },
    },
    {
        id: 'future-funk',
        name: 'Future Funk',
        isDark: true,
        colors: {
            background: '#2e1a47',
            cardBg: '#2e1a47',
            textPrimary: '#f7f2ea',
            textSecondary: '#c18fff',
            accent: '#f7f2ea',
            secondary: '#27173c',
            titleColor: '#f7f2ea',
            specialColor: 'linear-gradient(90deg, #f7f2ea, #c18fff)',
        },
    },
    {
        id: 'github',
        name: 'GitHub',
        isDark: true,
        colors: {
            background: '#212830',
            cardBg: '#212830',
            textPrimary: '#ccdae6',
            textSecondary: '#788386',
            accent: '#41ce5c',
            secondary: '#141b23',
            titleColor: '#41ce5c',
            specialColor: 'linear-gradient(90deg, #41ce5c, #ccdae6)',
        },
    },
    {
        id: 'godspeed',
        name: 'Godspeed',
        isDark: false,
        colors: {
            background: '#eae4cf',
            cardBg: '#eae4cf',
            textPrimary: '#5e5f62',
            textSecondary: '#807b66',
            accent: '#4e819e',
            secondary: '#ded9c9',
            titleColor: '#4e819e',
            specialColor: 'linear-gradient(90deg, #4e819e, #99760c)',
        },
    },
    {
        id: 'graen',
        name: 'Graen',
        isDark: true,
        colors: {
            background: '#303c36',
            cardBg: '#303c36',
            textPrimary: '#b7ac9c',
            textSecondary: '#7b9184',
            accent: '#a59682',
            secondary: '#36453c',
            titleColor: '#a59682',
            specialColor: 'linear-gradient(90deg, #a59682, #df6477)',
        },
    },
    {
        id: 'grand-prix',
        name: 'Grand Prix',
        isDark: true,
        colors: {
            background: '#36475c',
            cardBg: '#36475c',
            textPrimary: '#c1c7d7',
            textSecondary: '#94a2b2',
            accent: '#c0d036',
            secondary: '#42536b',
            titleColor: '#c0d036',
            specialColor: 'linear-gradient(90deg, #c0d036, #c1c7d7)',
        },
    },
    {
        id: 'grape',
        name: 'Grape',
        isDark: true,
        colors: {
            background: '#2c003e',
            cardBg: '#2c003e',
            textPrimary: '#ffffff',
            textSecondary: '#a7348f',
            accent: '#ff8f00',
            secondary: '#1f002d',
            titleColor: '#ff8f00',
            specialColor: 'linear-gradient(90deg, #ff8f00, #ffffff)',
        },
    },
    {
        id: 'graphite',
        name: 'Graphite',
        isDark: true,
        colors: {
            background: '#111111',
            cardBg: '#111111',
            textPrimary: '#eeeeee',
            textSecondary: '#656565',
            accent: '#eeeeee',
            secondary: '#191919',
            titleColor: '#eeeeee',
            specialColor: 'linear-gradient(90deg, #eeeeee, #656565)',
        },
    },
    {
        id: 'gruvbox-dark',
        name: 'Gruvbox Dark',
        isDark: true,
        colors: {
            background: '#282828',
            cardBg: '#282828',
            textPrimary: '#ebdbb2',
            textSecondary: '#7b6f65',
            accent: '#d79921',
            secondary: '#212121',
            titleColor: '#d79921',
            specialColor: 'linear-gradient(90deg, #d79921, #ebdbb2)',
        },
    },
    {
        id: 'gruvbox-light',
        name: 'Gruvbox Light',
        isDark: false,
        colors: {
            background: '#fbf1c7',
            cardBg: '#fbf1c7',
            textPrimary: '#3c3836',
            textSecondary: '#81715b',
            accent: '#527e54',
            secondary: '#daceae',
            titleColor: '#527e54',
            specialColor: 'linear-gradient(90deg, #527e54, #3c3836)',
        },
    },
    {
        id: 'hammerhead',
        name: 'Hammerhead',
        isDark: true,
        colors: {
            background: '#030613',
            cardBg: '#030613',
            textPrimary: '#e2f1f5',
            textSecondary: '#39688f',
            accent: '#4fcdb9',
            secondary: '#0a1928',
            titleColor: '#4fcdb9',
            specialColor: 'linear-gradient(90deg, #4fcdb9, #e2f1f5)',
        },
    },
    {
        id: 'hanok',
        name: 'Hanok',
        isDark: false,
        colors: {
            background: '#d8d2c3',
            cardBg: '#d8d2c3',
            textPrimary: '#393b3b',
            textSecondary: '#7f6554',
            accent: '#513a2a',
            secondary: '#cdc0af',
            titleColor: '#513a2a',
            specialColor: 'linear-gradient(90deg, #513a2a, #7f6554)',
        },
    },
    {
        id: 'hedge',
        name: 'Hedge',
        isDark: true,
        colors: {
            background: '#415e31',
            cardBg: '#415e31',
            textPrimary: '#f7f1d6',
            textSecondary: '#ede5b4',
            accent: '#84b369',
            secondary: '#38502a',
            titleColor: '#84b369',
            specialColor: 'linear-gradient(90deg, #84b369, #f2efbb)',
        },
    },
    {
        id: 'honey',
        name: 'Honey',
        isDark: false,
        colors: {
            background: '#f2aa00',
            cardBg: '#f2aa00',
            textPrimary: '#474010',
            textSecondary: '#7d5000',
            accent: '#615b00',
            secondary: '#e19e00',
            titleColor: '#615b00',
            specialColor: 'linear-gradient(90deg, #615b00, #474010)',
        },
    },
    {
        id: 'horizon',
        name: 'Horizon',
        isDark: true,
        colors: {
            background: '#1c1e26',
            cardBg: '#1c1e26',
            textPrimary: '#bbbbbb',
            textSecondary: '#db886f',
            accent: '#c4a88a',
            secondary: '#17181f',
            titleColor: '#c4a88a',
            specialColor: 'linear-gradient(90deg, #c4a88a, #bbbbbb)',
        },
    },
    {
        id: 'husqy',
        name: 'Husqy',
        isDark: true,
        colors: {
            background: '#000000',
            cardBg: '#000000',
            textPrimary: '#ebd7ff',
            textSecondary: '#972fff',
            accent: '#c58aff',
            secondary: '#1e001e',
            titleColor: '#c58aff',
            specialColor: 'linear-gradient(90deg, #c58aff, #ebd7ff)',
        },
    },
    {
        id: 'iceberg-dark',
        name: 'Iceberg Dark',
        isDark: true,
        colors: {
            background: '#161821',
            cardBg: '#161821',
            textPrimary: '#c6c8d1',
            textSecondary: '#686e89',
            accent: '#84a0c6',
            secondary: '#232531',
            titleColor: '#84a0c6',
            specialColor: 'linear-gradient(90deg, #84a0c6, #d2d4de)',
        },
    },
    {
        id: 'iceberg-light',
        name: 'Iceberg Light',
        isDark: false,
        colors: {
            background: '#e8e9ec',
            cardBg: '#e8e9ec',
            textPrimary: '#33374c',
            textSecondary: '#6b7295',
            accent: '#2d539e',
            secondary: '#ccceda',
            titleColor: '#2d539e',
            specialColor: 'linear-gradient(90deg, #2d539e, #262a3f)',
        },
    },
    {
        id: 'incognito',
        name: 'Incognito',
        isDark: true,
        colors: {
            background: '#0e0e0e',
            cardBg: '#0e0e0e',
            textPrimary: '#c6c6c6',
            textSecondary: '#636363',
            accent: '#ff9900',
            secondary: '#151515',
            titleColor: '#ff9900',
            specialColor: 'linear-gradient(90deg, #ff9900, #c6c6c6)',
        },
    },
    {
        id: 'ishtar',
        name: 'Ishtar',
        isDark: true,
        colors: {
            background: '#202020',
            cardBg: '#202020',
            textPrimary: '#fae1c3',
            textSecondary: '#847869',
            accent: '#da2312',
            secondary: '#272727',
            titleColor: '#da2312',
            specialColor: 'linear-gradient(90deg, #da2312, #c58940)',
        },
    },
    {
        id: 'iv-clover',
        name: 'IV Clover',
        isDark: false,
        colors: {
            background: '#a0a0a0',
            cardBg: '#a0a0a0',
            textPrimary: '#3b2d3b',
            textSecondary: '#353535',
            accent: '#573e40',
            secondary: '#bebebe',
            titleColor: '#573e40',
            specialColor: 'linear-gradient(90deg, #573e40, #353535)',
        },
    },
    {
        id: 'iv-spade',
        name: 'IV Spade',
        isDark: true,
        colors: {
            background: '#0c0c0c',
            cardBg: '#0c0c0c',
            textPrimary: '#d3c2c3',
            textSecondary: '#616161',
            accent: '#b7976a',
            secondary: '#121212',
            titleColor: '#b7976a',
            specialColor: 'linear-gradient(90deg, #b7976a, #bebebe)',
        },
    },
    {
        id: 'joker',
        name: 'Joker',
        isDark: true,
        colors: {
            background: '#1a0e25',
            cardBg: '#1a0e25',
            textPrimary: '#e9e2f5',
            textSecondary: '#7554a3',
            accent: '#99de1e',
            secondary: '#14081f',
            titleColor: '#99de1e',
            specialColor: 'linear-gradient(90deg, #99de1e, #e9e2f5)',
        },
    },
    {
        id: 'laser',
        name: 'Laser',
        isDark: true,
        colors: {
            background: '#221b44',
            cardBg: '#221b44',
            textPrimary: '#dbe7e8',
            textSecondary: '#ca265e',
            accent: '#009eaf',
            secondary: '#1e173b',
            titleColor: '#009eaf',
            specialColor: 'linear-gradient(90deg, #009eaf, #dbe7e8)',
        },
    },
    {
        id: 'lavender',
        name: 'Lavender',
        isDark: false,
        colors: {
            background: '#ada6c2',
            cardBg: '#ada6c2',
            textPrimary: '#2f2a41',
            textSecondary: '#524e64',
            accent: '#524e64',
            secondary: '#a19bb9',
            titleColor: '#524e64',
            specialColor: 'linear-gradient(90deg, #524e64, #2f2a41)',
        },
    },
    {
        id: 'leather',
        name: 'Leather',
        isDark: false,
        colors: {
            background: '#a86948',
            cardBg: '#a86948',
            textPrimary: '#ffffff',
            textSecondary: '#371e12',
            accent: '#ffe4bc',
            secondary: '#9a5f3f',
            titleColor: '#ffe4bc',
            specialColor: 'linear-gradient(90deg, #ffe4bc, #ffffff)',
        },
    },
    {
        id: 'lil-dragon',
        name: 'Lil Dragon',
        isDark: false,
        colors: {
            background: '#ebe1ef',
            cardBg: '#ebe1ef',
            textPrimary: '#212b43',
            textSecondary: '#8367a0',
            accent: '#8858d5',
            secondary: '#dac7e2',
            titleColor: '#8858d5',
            specialColor: 'linear-gradient(90deg, #8858d5, #212b43)',
        },
    },
    {
        id: 'lilac-mist',
        name: 'Lilac Mist',
        isDark: false,
        colors: {
            background: '#fffbfe',
            cardBg: '#fffbfe',
            textPrimary: '#5c2954',
            textSecondary: '#cd539d',
            accent: '#b94189',
            secondary: '#ecdcee',
            titleColor: '#b94189',
            specialColor: 'linear-gradient(90deg, #b94189, #5c2954)',
        },
    },
    {
        id: 'lime',
        name: 'Lime',
        isDark: false,
        colors: {
            background: '#7c878e',
            cardBg: '#7c878e',
            textPrimary: '#0c1116',
            textSecondary: '#2f3337',
            accent: '#e0eeca',
            secondary: '#737d82',
            titleColor: '#e0eeca',
            specialColor: 'linear-gradient(90deg, #e0eeca, #0c1116)',
        },
    },
    {
        id: 'luna',
        name: 'Luna',
        isDark: true,
        colors: {
            background: '#221c35',
            cardBg: '#221c35',
            textPrimary: '#ffe3eb',
            textSecondary: '#885fb5',
            accent: '#f67599',
            secondary: '#2f2346',
            titleColor: '#f67599',
            specialColor: 'linear-gradient(90deg, #f67599, #ffe3eb)',
        },
    },
    {
        id: 'magic-girl',
        name: 'Magic Girl',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#007d66',
            textSecondary: '#229d7f',
            accent: '#e95791',
            secondary: '#f2f2f2',
            titleColor: '#e95791',
            specialColor: 'linear-gradient(90deg, #e95791, #007d66)',
        },
    },
    {
        id: 'mashu',
        name: 'Mashu',
        isDark: true,
        colors: {
            background: '#2b2b2c',
            cardBg: '#2b2b2c',
            textPrimary: '#f1e2e4',
            textSecondary: '#d8a0a6',
            accent: '#7a6c9d',
            secondary: '#27242c',
            titleColor: '#7a6c9d',
            specialColor: 'linear-gradient(90deg, #7a6c9d, #f1e2e4)',
        },
    },
    {
        id: 'matcha-brownie',
        name: 'Matcha Brownie',
        isDark: true,
        colors: {
            background: '#523525',
            cardBg: '#523525',
            textPrimary: '#ecddcc',
            textSecondary: '#b27858',
            accent: '#7ec160',
            secondary: '#422b1e',
            titleColor: '#7ec160',
            specialColor: 'linear-gradient(90deg, #7ec160, #ecddcc)',
        },
    },
    {
        id: 'material',
        name: 'Material',
        isDark: true,
        colors: {
            background: '#263238',
            cardBg: '#263238',
            textPrimary: '#e6edf3',
            textSecondary: '#658997',
            accent: '#80cbc4',
            secondary: '#2e3c43',
            titleColor: '#80cbc4',
            specialColor: 'linear-gradient(90deg, #80cbc4, #e6edf3)',
        },
    },
    {
        id: 'matrix',
        name: 'Matrix',
        isDark: true,
        colors: {
            background: '#000000',
            cardBg: '#000000',
            textPrimary: '#d1ffcd',
            textSecondary: '#007700',
            accent: '#15ff00',
            secondary: '#032000',
            titleColor: '#15ff00',
            specialColor: 'linear-gradient(90deg, #15ff00, #d1ffcd)',
        },
    },
    {
        id: 'menthol',
        name: 'Menthol',
        isDark: false,
        colors: {
            background: '#00c18c',
            cardBg: '#00c18c',
            textPrimary: '#323232',
            textSecondary: '#15573b',
            accent: '#4c4c4c',
            secondary: '#17ae7d',
            titleColor: '#4c4c4c',
            specialColor: 'linear-gradient(90deg, #4c4c4c, #025838)',
        },
    },
    {
        id: 'metaverse',
        name: 'Metaverse',
        isDark: true,
        colors: {
            background: '#232323',
            cardBg: '#232323',
            textPrimary: '#e8e8e8',
            textSecondary: '#6d6d6d',
            accent: '#d82934',
            secondary: '#1d1d1d',
            titleColor: '#d82934',
            specialColor: 'linear-gradient(90deg, #d82934, #e8e8e8)',
        },
    },
    {
        id: 'metropolis',
        name: 'Metropolis',
        isDark: true,
        colors: {
            background: '#0f1f2c',
            cardBg: '#0f1f2c',
            textPrimary: '#e4edf1',
            textSecondary: '#356f8b',
            accent: '#56c3b7',
            secondary: '#0b1822',
            titleColor: '#56c3b7',
            specialColor: 'linear-gradient(90deg, #56c3b7, #e4edf1)',
        },
    },
    {
        id: 'mexican',
        name: 'Mexican',
        isDark: false,
        colors: {
            background: '#f8ad34',
            cardBg: '#f8ad34',
            textPrimary: '#4c4c4c',
            textSecondary: '#333333',
            accent: '#b12189',
            secondary: '#f9b951',
            titleColor: '#b12189',
            specialColor: 'linear-gradient(90deg, #b12189, #666666)',
        },
    },
    {
        id: 'miami',
        name: 'Miami',
        isDark: false,
        colors: {
            background: '#f35588',
            cardBg: '#f35588',
            textPrimary: '#1d1417',
            textSecondary: '#631c33',
            accent: '#013d3b',
            secondary: '#db4979',
            titleColor: '#013d3b',
            specialColor: 'linear-gradient(90deg, #013d3b, #e2fdeb)',
        },
    },
    {
        id: 'miami-nights',
        name: 'Miami Nights',
        isDark: true,
        colors: {
            background: '#18181a',
            cardBg: '#18181a',
            textPrimary: '#ffffff',
            textSecondary: '#47bac0',
            accent: '#e4609b',
            secondary: '#0f0f10',
            titleColor: '#e4609b',
            specialColor: 'linear-gradient(90deg, #e4609b, #ffffff)',
        },
    },
    {
        id: 'midnight',
        name: 'Midnight',
        isDark: true,
        colors: {
            background: '#0b0e13',
            cardBg: '#0b0e13',
            textPrimary: '#9fadc6',
            textSecondary: '#516689',
            accent: '#60759f',
            secondary: '#141a24',
            titleColor: '#60759f',
            specialColor: 'linear-gradient(90deg, #60759f, #9fadc6)',
        },
    },
    {
        id: 'milkshake',
        name: 'Milkshake',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#212b43',
            textSecondary: '#1c94ae',
            accent: '#212b43',
            secondary: '#ddeff3',
            titleColor: '#212b43',
            specialColor: 'linear-gradient(90deg, #212b43, #1c94ae)',
        },
    },
    {
        id: 'mint',
        name: 'Mint',
        isDark: true,
        colors: {
            background: '#05385b',
            cardBg: '#05385b',
            textPrimary: '#edf5e1',
            textSecondary: '#2987b2',
            accent: '#5cdb95',
            secondary: '#07324e',
            titleColor: '#5cdb95',
            specialColor: 'linear-gradient(90deg, #5cdb95, #edf5e1)',
        },
    },
    {
        id: 'mizu',
        name: 'Mizu',
        isDark: false,
        colors: {
            background: '#afcbdd',
            cardBg: '#afcbdd',
            textPrimary: '#1a2633',
            textSecondary: '#486a82',
            accent: '#736626',
            secondary: '#9fc1d4',
            titleColor: '#736626',
            specialColor: 'linear-gradient(90deg, #736626, #1a2633)',
        },
    },
    {
        id: 'modern-dolch',
        name: 'Modern Dolch',
        isDark: true,
        colors: {
            background: '#2d2e30',
            cardBg: '#2d2e30',
            textPrimary: '#e3e6eb',
            textSecondary: '#72777c',
            accent: '#7eddd3',
            secondary: '#242527',
            titleColor: '#7eddd3',
            specialColor: 'linear-gradient(90deg, #7eddd3, #e3e6eb)',
        },
    },
    {
        id: 'modern-dolch-light',
        name: 'Modern Dolch Light',
        isDark: false,
        colors: {
            background: '#dbdbdb',
            cardBg: '#dbdbdb',
            textPrimary: '#454545',
            textSecondary: '#7d7c7c',
            accent: '#388978',
            secondary: '#e8e8e8',
            titleColor: '#388978',
            specialColor: 'linear-gradient(90deg, #388978, #454545)',
        },
    },
    {
        id: 'modern-ink',
        name: 'Modern Ink',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#000000',
            textSecondary: '#888888',
            accent: '#ff360d',
            secondary: '#ececec',
            titleColor: '#ff360d',
            specialColor: 'linear-gradient(90deg, #ff360d, #000000)',
        },
    },
    {
        id: 'moonlight',
        name: 'Moonlight',
        isDark: true,
        colors: {
            background: '#191f28',
            cardBg: '#191f28',
            textPrimary: '#ccccb5',
            textSecondary: '#59698a',
            accent: '#c69f68',
            secondary: '#141a22',
            titleColor: '#c69f68',
            specialColor: 'linear-gradient(90deg, #c69f68, #8f744b)',
        },
    },
    {
        id: 'mountain',
        name: 'Mountain',
        isDark: true,
        colors: {
            background: '#0f0f0f',
            cardBg: '#0f0f0f',
            textPrimary: '#e7e7e7',
            textSecondary: '#666666',
            accent: '#e7e7e7',
            secondary: '#1a1a1a',
            titleColor: '#e7e7e7',
            specialColor: 'linear-gradient(90deg, #e7e7e7, #666666)',
        },
    },
    {
        id: 'mr-sleeves',
        name: 'Mr Sleeves',
        isDark: false,
        colors: {
            background: '#d1d7da',
            cardBg: '#d1d7da',
            textPrimary: '#1d1d1d',
            textSecondary: '#6b7073',
            accent: '#ac5840',
            secondary: '#bfcbd1',
            titleColor: '#ac5840',
            specialColor: 'linear-gradient(90deg, #ac5840, #4a739a)',
        },
    },
    {
        id: 'ms-cupcakes',
        name: 'Ms Cupcakes',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#0a282f',
            textSecondary: '#d64090',
            accent: '#0e9bbf',
            secondary: '#edf8fa',
            titleColor: '#0e9bbf',
            specialColor: 'linear-gradient(90deg, #0e9bbf, #303030)',
        },
    },
    {
        id: 'muted',
        name: 'Muted',
        isDark: true,
        colors: {
            background: '#525252',
            cardBg: '#525252',
            textPrimary: '#b1e4e3',
            textSecondary: '#97a2b1',
            accent: '#c5b4e3',
            secondary: '#494949',
            titleColor: '#c5b4e3',
            specialColor: 'linear-gradient(90deg, #c5b4e3, #97a2b1)',
        },
    },
    {
        id: 'nautilus',
        name: 'Nautilus',
        isDark: true,
        colors: {
            background: '#132237',
            cardBg: '#132237',
            textPrimary: '#1cbaac',
            textSecondary: '#1072a1',
            accent: '#ebb723',
            secondary: '#0e1a29',
            titleColor: '#ebb723',
            specialColor: 'linear-gradient(90deg, #ebb723, #1cbaac)',
        },
    },
    {
        id: 'nebula',
        name: 'Nebula',
        isDark: true,
        colors: {
            background: '#212135',
            cardBg: '#212135',
            textPrimary: '#878a8a',
            textSecondary: '#19b3b8',
            accent: '#be3c88',
            secondary: '#191928',
            titleColor: '#be3c88',
            specialColor: 'linear-gradient(90deg, #be3c88, #78c729)',
        },
    },
    {
        id: 'night-runner',
        name: 'Night Runner',
        isDark: true,
        colors: {
            background: '#212121',
            cardBg: '#212121',
            textPrimary: '#e8e8e8',
            textSecondary: '#705eb2',
            accent: '#feff04',
            secondary: '#1a1a1a',
            titleColor: '#feff04',
            specialColor: 'linear-gradient(90deg, #feff04, #e8e8e8)',
        },
    },
    {
        id: 'nord-light',
        name: 'Nord Light',
        isDark: false,
        colors: {
            background: '#eceff4',
            cardBg: '#eceff4',
            textPrimary: '#3f6969',
            textSecondary: '#6a7791',
            accent: '#518786',
            secondary: '#d8dee9',
            titleColor: '#518786',
            specialColor: 'linear-gradient(90deg, #518786, #3f6969)',
        },
    },
    {
        id: 'norse',
        name: 'Norse',
        isDark: true,
        colors: {
            background: '#242425',
            cardBg: '#242425',
            textPrimary: '#ccc2b1',
            textSecondary: '#6e7e82',
            accent: '#3c8498',
            secondary: '#303333',
            titleColor: '#3c8498',
            specialColor: 'linear-gradient(90deg, #3c8498, #ccc2b1)',
        },
    },
    {
        id: 'oblivion',
        name: 'Oblivion',
        isDark: true,
        colors: {
            background: '#313231',
            cardBg: '#313231',
            textPrimary: '#f7f5f1',
            textSecondary: '#7f8587',
            accent: '#a5a096',
            secondary: '#3a3b3b',
            titleColor: '#a5a096',
            specialColor: 'linear-gradient(90deg, #a5a096, #f7f5f1)',
        },
    },
    {
        id: 'olive',
        name: 'Olive',
        isDark: false,
        colors: {
            background: '#e9e5cc',
            cardBg: '#e9e5cc',
            textPrimary: '#373731',
            textSecondary: '#7a745a',
            accent: '#747658',
            secondary: '#d4cfbc',
            titleColor: '#747658',
            specialColor: 'linear-gradient(90deg, #747658, #373731)',
        },
    },
    {
        id: 'olivia',
        name: 'Olivia',
        isDark: true,
        colors: {
            background: '#1c1b1d',
            cardBg: '#1c1b1d',
            textPrimary: '#f2efed',
            textSecondary: '#806666',
            accent: '#deaf9d',
            secondary: '#262223',
            titleColor: '#deaf9d',
            specialColor: 'linear-gradient(90deg, #deaf9d, #f2efed)',
        },
    },
    {
        id: 'onedark',
        name: 'One Dark',
        isDark: true,
        colors: {
            background: '#2f343f',
            cardBg: '#2f343f',
            textPrimary: '#98c379',
            textSecondary: '#eceff4',
            accent: '#61afef',
            secondary: '#262b34',
            titleColor: '#61afef',
            specialColor: 'linear-gradient(90deg, #61afef, #98c379)',
        },
    },
    {
        id: 'our-theme',
        name: 'Our Theme',
        isDark: true,
        colors: {
            background: '#ce1226',
            cardBg: '#ce1226',
            textPrimary: '#ffffff',
            textSecondary: '#f3abb2',
            accent: '#fcd116',
            secondary: '#9f1020',
            titleColor: '#fcd116',
            specialColor: 'linear-gradient(90deg, #fcd116, #ffffff)',
        },
    },
    {
        id: 'pale-nimbus',
        name: 'Pale Nimbus',
        isDark: true,
        colors: {
            background: '#433e4c',
            cardBg: '#433e4c',
            textPrimary: '#feffdb',
            textSecondary: '#ffaca3',
            accent: '#94ffc2',
            secondary: '#694f5e',
            titleColor: '#94ffc2',
            specialColor: 'linear-gradient(90deg, #94ffc2, #feffdb)',
        },
    },
    {
        id: 'paper',
        name: 'Paper',
        isDark: false,
        colors: {
            background: '#eeeeee',
            cardBg: '#eeeeee',
            textPrimary: '#444444',
            textSecondary: '#7d7d7d',
            accent: '#444444',
            secondary: '#dddddd',
            titleColor: '#444444',
            specialColor: 'linear-gradient(90deg, #444444, #7d7d7d)',
        },
    },
    {
        id: 'passion-fruit',
        name: 'Passion Fruit',
        isDark: true,
        colors: {
            background: '#7c2142',
            cardBg: '#7c2142',
            textPrimary: '#ffffff',
            textSecondary: '#a4a0c0',
            accent: '#f4a3b4',
            secondary: '#833c5e',
            titleColor: '#f4a3b4',
            specialColor: 'linear-gradient(90deg, #f4a3b4, #ffffff)',
        },
    },
    {
        id: 'pastel',
        name: 'Pastel',
        isDark: false,
        colors: {
            background: '#e0b2bd',
            cardBg: '#e0b2bd',
            textPrimary: '#493d4a',
            textSecondary: '#00618a',
            accent: '#655c06',
            secondary: '#d29fab',
            titleColor: '#655c06',
            specialColor: 'linear-gradient(90deg, #655c06, #493d4a)',
        },
    },
    {
        id: 'peach-blossom',
        name: 'Peach Blossom',
        isDark: true,
        colors: {
            background: '#292929',
            cardBg: '#292929',
            textPrimary: '#fecea8',
            textSecondary: '#7d7d7d',
            accent: '#99b898',
            secondary: '#2a363b',
            titleColor: '#99b898',
            specialColor: 'linear-gradient(90deg, #99b898, #7d7d7d)',
        },
    },
    {
        id: 'peaches',
        name: 'Peaches',
        isDark: false,
        colors: {
            background: '#e0d7c1',
            cardBg: '#e0d7c1',
            textPrimary: '#5f4c41',
            textSecondary: '#af5d25',
            accent: '#c54b2a',
            secondary: '#e2caaf',
            titleColor: '#c54b2a',
            specialColor: 'linear-gradient(90deg, #c54b2a, #5f4c41)',
        },
    },
    {
        id: 'phantom',
        name: 'Phantom',
        isDark: true,
        colors: {
            background: '#000011',
            cardBg: '#000011',
            textPrimary: '#c0caf5',
            textSecondary: '#656f9f',
            accent: '#7aa2f7',
            secondary: '#24283b',
            titleColor: '#7aa2f7',
            specialColor: 'linear-gradient(90deg, #7aa2f7, #bb9af7)',
        },
    },
    {
        id: 'pink-lemonade',
        name: 'Pink Lemonade',
        isDark: false,
        colors: {
            background: '#f6d992',
            cardBg: '#f6d992',
            textPrimary: '#5d5d28',
            textSecondary: '#cf4a11',
            accent: '#e13113',
            secondary: '#f6cc93',
            titleColor: '#e13113',
            specialColor: 'linear-gradient(90deg, #e13113, #797934)',
        },
    },
    {
        id: 'pulse',
        name: 'Pulse',
        isDark: true,
        colors: {
            background: '#181818',
            cardBg: '#181818',
            textPrimary: '#e5f4f4',
            textSecondary: '#616569',
            accent: '#17b8bd',
            secondary: '#121212',
            titleColor: '#17b8bd',
            specialColor: 'linear-gradient(90deg, #17b8bd, #e5f4f4)',
        },
    },
    {
        id: 'purpleish',
        name: 'Purpleish',
        isDark: true,
        colors: {
            background: '#1e1e32',
            cardBg: '#1e1e32',
            textPrimary: '#a3a3cc',
            textSecondary: '#6464a1',
            accent: '#7a52cc',
            secondary: '#181829',
            titleColor: '#7a52cc',
            specialColor: 'linear-gradient(90deg, #7a52cc, #a3a3cc)',
        },
    },
    {
        id: 'rainbow-trail',
        name: 'Rainbow Trail',
        isDark: false,
        colors: {
            background: '#f5f5f5',
            cardBg: '#f5f5f5',
            textPrimary: '#1f1f1f',
            textSecondary: '#4f4f4f',
            accent: '#363636',
            secondary: '#e0e0e0',
            titleColor: '#363636',
            specialColor: 'linear-gradient(90deg, #363636, #0d0d0d)',
        },
    },
    {
        id: 'red-dragon',
        name: 'Red Dragon',
        isDark: true,
        colors: {
            background: '#1a0b0c',
            cardBg: '#1a0b0c',
            textPrimary: '#777c7d',
            textSecondary: '#e2a528',
            accent: '#ff3a32',
            secondary: '#0e0506',
            titleColor: '#ff3a32',
            specialColor: 'linear-gradient(90deg, #ff3a32, #777c7d)',
        },
    },
    {
        id: 'red-samurai',
        name: 'Red Samurai',
        isDark: true,
        colors: {
            background: '#84202c',
            cardBg: '#84202c',
            textPrimary: '#e2dad0',
            textSecondary: '#df6f7c',
            accent: '#c79e6e',
            secondary: '#751d26',
            titleColor: '#c79e6e',
            specialColor: 'linear-gradient(90deg, #c79e6e, #e2dad0)',
        },
    },
    {
        id: 'repose-dark',
        name: 'Repose Dark',
        isDark: true,
        colors: {
            background: '#2f3338',
            cardBg: '#2f3338',
            textPrimary: '#d6d2bc',
            textSecondary: '#8f8e84',
            accent: '#d6d2bc',
            secondary: '#3a3c3d',
            titleColor: '#d6d2bc',
            specialColor: 'linear-gradient(90deg, #d6d2bc, #8f8e84)',
        },
    },
    {
        id: 'repose-light',
        name: 'Repose Light',
        isDark: false,
        colors: {
            background: '#efead0',
            cardBg: '#efead0',
            textPrimary: '#333538',
            textSecondary: '#7a7970',
            accent: '#5f605e',
            secondary: '#dbd6c4',
            titleColor: '#5f605e',
            specialColor: 'linear-gradient(90deg, #5f605e, #333538)',
        },
    },
    {
        id: 'retro',
        name: 'Retro',
        isDark: false,
        colors: {
            background: '#dad3c1',
            cardBg: '#dad3c1',
            textPrimary: '#1d1b17',
            textSecondary: '#716b5f',
            accent: '#1d1b17',
            secondary: '#c8c3b3',
            titleColor: '#1d1b17',
            specialColor: 'linear-gradient(90deg, #1d1b17, #716b5f)',
        },
    },
    {
        id: 'retrocast',
        name: 'Retrocast',
        isDark: true,
        colors: {
            background: '#07737a',
            cardBg: '#07737a',
            textPrimary: '#ffffff',
            textSecondary: '#f3e03b',
            accent: '#9de2e5',
            secondary: '#26858b',
            titleColor: '#9de2e5',
            specialColor: 'linear-gradient(90deg, #9de2e5, #ffffff)',
        },
    },
    {
        id: 'rgb',
        name: 'RGB',
        isDark: true,
        colors: {
            background: '#111111',
            cardBg: '#111111',
            textPrimary: '#eeeeee',
            textSecondary: '#666666',
            accent: '#eeeeee',
            secondary: '#1a1a1a',
            titleColor: '#eeeeee',
            specialColor: 'linear-gradient(90deg, #eeeeee, #666666)',
        },
    },
    {
        id: 'rose-pine',
        name: 'Rose Pine',
        isDark: true,
        colors: {
            background: '#1f1d27',
            cardBg: '#1f1d27',
            textPrimary: '#e0def4',
            textSecondary: '#c4a7e7',
            accent: '#9ccfd8',
            secondary: '#282533',
            titleColor: '#9ccfd8',
            specialColor: 'linear-gradient(90deg, #9ccfd8, #f6c177)',
        },
    },
    {
        id: 'rose-pine-dawn',
        name: 'Rose Pine Dawn',
        isDark: false,
        colors: {
            background: '#fffaf3',
            cardBg: '#fffaf3',
            textPrimary: '#286983',
            textSecondary: '#9f70d8',
            accent: '#538f9a',
            secondary: '#f0e9df',
            titleColor: '#538f9a',
            specialColor: 'linear-gradient(90deg, #538f9a, #be7614)',
        },
    },
    {
        id: 'rose-pine-moon',
        name: 'Rose Pine Moon',
        isDark: true,
        colors: {
            background: '#2a273f',
            cardBg: '#2a273f',
            textPrimary: '#e0def4',
            textSecondary: '#c4a7e7',
            accent: '#9ccfd8',
            secondary: '#211f32',
            titleColor: '#9ccfd8',
            specialColor: 'linear-gradient(90deg, #9ccfd8, #f6c177)',
        },
    },
    {
        id: 'rudy',
        name: 'Rudy',
        isDark: true,
        colors: {
            background: '#1a2b3e',
            cardBg: '#1a2b3e',
            textPrimary: '#c9c8bf',
            textSecondary: '#54759d',
            accent: '#af8f5c',
            secondary: '#152231',
            titleColor: '#af8f5c',
            specialColor: 'linear-gradient(90deg, #af8f5c, #c9c8bf)',
        },
    },
    {
        id: 'ryujinscales',
        name: 'Ryujinscales',
        isDark: true,
        colors: {
            background: '#081426',
            cardBg: '#081426',
            textPrimary: '#ffe4bc',
            textSecondary: '#ffbc90',
            accent: '#f17754',
            secondary: '#040e1d',
            titleColor: '#f17754',
            specialColor: 'linear-gradient(90deg, #f17754, #ffe4bc)',
        },
    },
    {
        id: 'serika',
        name: 'Serika',
        isDark: false,
        colors: {
            background: '#e1e1e3',
            cardBg: '#e1e1e3',
            textPrimary: '#323437',
            textSecondary: '#72777f',
            accent: '#8f740d',
            secondary: '#d1d3d8',
            titleColor: '#8f740d',
            specialColor: 'linear-gradient(90deg, #8f740d, #323437)',
        },
    },
    {
        id: 'sewing-tin',
        name: 'Sewing Tin',
        isDark: true,
        colors: {
            background: '#241963',
            cardBg: '#241963',
            textPrimary: '#ffffff',
            textSecondary: '#5477d9',
            accent: '#f2ce83',
            secondary: '#2a277a',
            titleColor: '#f2ce83',
            specialColor: 'linear-gradient(90deg, #f2ce83, #ffffff)',
        },
    },
    {
        id: 'sewing-tin-light',
        name: 'Sewing Tin Light',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#2d2076',
            textSecondary: '#385eca',
            accent: '#2d2076',
            secondary: '#c8cedf',
            titleColor: '#2d2076',
            specialColor: 'linear-gradient(90deg, #2d2076, #966c05)',
        },
    },
    {
        id: 'shadow',
        name: 'Shadow',
        isDark: true,
        colors: {
            background: '#000000',
            cardBg: '#000000',
            textPrimary: '#eeeeee',
            textSecondary: '#646464',
            accent: '#eeeeee',
            secondary: '#171717',
            titleColor: '#eeeeee',
            specialColor: 'linear-gradient(90deg, #eeeeee, #646464)',
        },
    },
    {
        id: 'shoko',
        name: 'Shoko',
        isDark: false,
        colors: {
            background: '#ced7e0',
            cardBg: '#ced7e0',
            textPrimary: '#3b4c58',
            textSecondary: '#4f738b',
            accent: '#287794',
            secondary: '#b7cada',
            titleColor: '#287794',
            specialColor: 'linear-gradient(90deg, #287794, #3b4c58)',
        },
    },
    {
        id: 'slambook',
        name: 'Slambook',
        isDark: false,
        colors: {
            background: '#fffdde',
            cardBg: '#fffdde',
            textPrimary: '#13005a',
            textSecondary: '#1c82ad',
            accent: '#03001c',
            secondary: '#c6dce4',
            titleColor: '#03001c',
            specialColor: 'linear-gradient(90deg, #03001c, #367e18)',
        },
    },
    {
        id: 'snes',
        name: 'SNES',
        isDark: false,
        colors: {
            background: '#bfbec2',
            cardBg: '#bfbec2',
            textPrimary: '#2e2e2e',
            textSecondary: '#6a49bc',
            accent: '#553d94',
            secondary: '#b5b0c2',
            titleColor: '#553d94',
            specialColor: 'linear-gradient(90deg, #553d94, #2e2e2e)',
        },
    },
    {
        id: 'soaring-skies',
        name: 'Soaring Skies',
        isDark: false,
        colors: {
            background: '#fff9f2',
            cardBg: '#fff9f2',
            textPrimary: '#1d1e1e',
            textSecondary: '#1e107a',
            accent: '#1088b4',
            secondary: '#e5ddd4',
            titleColor: '#1088b4',
            specialColor: 'linear-gradient(90deg, #1088b4, #1e107a)',
        },
    },
    {
        id: 'solarized-dark',
        name: 'Solarized Dark',
        isDark: true,
        colors: {
            background: '#002b36',
            cardBg: '#002b36',
            textPrimary: '#2f93d9',
            textSecondary: '#2aa198',
            accent: '#859900',
            secondary: '#00222b',
            titleColor: '#859900',
            specialColor: 'linear-gradient(90deg, #859900, #dc322f)',
        },
    },
    {
        id: 'solarized-light',
        name: 'Solarized Light',
        isDark: false,
        colors: {
            background: '#fdf6e3',
            cardBg: '#fdf6e3',
            textPrimary: '#181819',
            textSecondary: '#248881',
            accent: '#718200',
            secondary: '#e2d8be',
            titleColor: '#718200',
            specialColor: 'linear-gradient(90deg, #718200, #dc322f)',
        },
    },
    {
        id: 'solarized-osaka',
        name: 'Solarized Osaka',
        isDark: true,
        colors: {
            background: '#00141a',
            cardBg: '#00141a',
            textPrimary: '#eee8d5',
            textSecondary: '#2aa198',
            accent: '#859900',
            secondary: '#00222b',
            titleColor: '#859900',
            specialColor: 'linear-gradient(90deg, #859900, #eee8d5)',
        },
    },
    {
        id: 'sonokai',
        name: 'Sonokai',
        isDark: true,
        colors: {
            background: '#2c2e34',
            cardBg: '#2c2e34',
            textPrimary: '#e2e2e3',
            textSecondary: '#e7c664',
            accent: '#9ed072',
            secondary: '#232429',
            titleColor: '#9ed072',
            specialColor: 'linear-gradient(90deg, #9ed072, #f38c71)',
        },
    },
    {
        id: 'spiderman',
        name: 'Spiderman',
        isDark: true,
        colors: {
            background: '#0d1219',
            cardBg: '#0d1219',
            textPrimary: '#f0f0f0',
            textSecondary: '#0476f2',
            accent: '#e23636',
            secondary: '#0b1c2e',
            titleColor: '#e23636',
            specialColor: 'linear-gradient(90deg, #e23636, #f0f0f0)',
        },
    },
    {
        id: 'stealth',
        name: 'Stealth',
        isDark: true,
        colors: {
            background: '#010203',
            cardBg: '#010203',
            textPrimary: '#727e87',
            textSecondary: '#5e676e',
            accent: '#596268',
            secondary: '#121212',
            titleColor: '#596268',
            specialColor: 'linear-gradient(90deg, #596268, #e25303)',
        },
    },
    {
        id: 'strawberry',
        name: 'Strawberry',
        isDark: false,
        colors: {
            background: '#f37f83',
            cardBg: '#f37f83',
            textPrimary: '#313115',
            textSecondary: '#931429',
            accent: '#4c4c21',
            secondary: '#ef6e77',
            titleColor: '#4c4c21',
            specialColor: 'linear-gradient(90deg, #4c4c21, #931429)',
        },
    },
    {
        id: 'striker',
        name: 'Striker',
        isDark: true,
        colors: {
            background: '#124883',
            cardBg: '#124883',
            textPrimary: '#d6dbd9',
            textSecondary: '#5597de',
            accent: '#d7dcda',
            secondary: '#104176',
            titleColor: '#d7dcda',
            specialColor: 'linear-gradient(90deg, #d7dcda, #5597de)',
        },
    },
    {
        id: 'suisei',
        name: 'Suisei',
        isDark: true,
        colors: {
            background: '#3b4a62',
            cardBg: '#3b4a62',
            textPrimary: '#dbdeeb',
            textSecondary: '#fe9841',
            accent: '#bef0ff',
            secondary: '#313e55',
            titleColor: '#bef0ff',
            specialColor: 'linear-gradient(90deg, #bef0ff, #fe9841)',
        },
    },
    {
        id: 'sunset',
        name: 'Sunset',
        isDark: true,
        colors: {
            background: '#211e24',
            cardBg: '#211e24',
            textPrimary: '#f4e0c9',
            textSecondary: '#67639f',
            accent: '#f79777',
            secondary: '#161319',
            titleColor: '#f79777',
            specialColor: 'linear-gradient(90deg, #f79777, #f4e0c9)',
        },
    },
    {
        id: 'superuser',
        name: 'Superuser',
        isDark: true,
        colors: {
            background: '#262a33',
            cardBg: '#262a33',
            textPrimary: '#e5f7ef',
            textSecondary: '#5e7688',
            accent: '#43ffaf',
            secondary: '#1f232c',
            titleColor: '#43ffaf',
            specialColor: 'linear-gradient(90deg, #43ffaf, #e5f7ef)',
        },
    },
    {
        id: 'sweden',
        name: 'Sweden',
        isDark: true,
        colors: {
            background: '#0058a3',
            cardBg: '#0058a3',
            textPrimary: '#ffffff',
            textSecondary: '#62b1dd',
            accent: '#ffcc02',
            secondary: '#024f8e',
            titleColor: '#ffcc02',
            specialColor: 'linear-gradient(90deg, #ffcc02, #b5b5b5)',
        },
    },
    {
        id: 'tangerine',
        name: 'Tangerine',
        isDark: false,
        colors: {
            background: '#ffede0',
            cardBg: '#ffede0',
            textPrimary: '#3d1705',
            textSecondary: '#df4800',
            accent: '#de4901',
            secondary: '#fdd3bf',
            titleColor: '#de4901',
            specialColor: 'linear-gradient(90deg, #de4901, #5d8500)',
        },
    },
    {
        id: 'taro',
        name: 'Taro',
        isDark: false,
        colors: {
            background: '#b3baff',
            cardBg: '#b3baff',
            textPrimary: '#130f1a',
            textSecondary: '#595775',
            accent: '#130f1a',
            secondary: '#a3a7df',
            titleColor: '#130f1a',
            specialColor: 'linear-gradient(90deg, #130f1a, #006564)',
        },
    },
    {
        id: 'terminal',
        name: 'Terminal',
        isDark: true,
        colors: {
            background: '#191a1b',
            cardBg: '#191a1b',
            textPrimary: '#e7eae0',
            textSecondary: '#646668',
            accent: '#79a617',
            secondary: '#141516',
            titleColor: '#79a617',
            specialColor: 'linear-gradient(90deg, #79a617, #e7eae0)',
        },
    },
    {
        id: 'terra',
        name: 'Terra',
        isDark: true,
        colors: {
            background: '#0c100e',
            cardBg: '#0c100e',
            textPrimary: '#f0edd1',
            textSecondary: '#4d6f2f',
            accent: '#89c559',
            secondary: '#0f1d18',
            titleColor: '#89c559',
            specialColor: 'linear-gradient(90deg, #89c559, #f0edd1)',
        },
    },
    {
        id: 'terrazzo',
        name: 'Terrazzo',
        isDark: false,
        colors: {
            background: '#f1e5da',
            cardBg: '#f1e5da',
            textPrimary: '#023e3b',
            textSecondary: '#5d7e7f',
            accent: '#c95423',
            secondary: '#e3d3c6',
            titleColor: '#c95423',
            specialColor: 'linear-gradient(90deg, #c95423, #023e3b)',
        },
    },
    {
        id: 'terror-below',
        name: 'Terror Below',
        isDark: true,
        colors: {
            background: '#0b1e1a',
            cardBg: '#0b1e1a',
            textPrimary: '#dceae5',
            textSecondary: '#017367',
            accent: '#66ac92',
            secondary: '#041715',
            titleColor: '#66ac92',
            specialColor: 'linear-gradient(90deg, #66ac92, #dceae5)',
        },
    },
    {
        id: 'tiramisu',
        name: 'Tiramisu',
        isDark: false,
        colors: {
            background: '#cfc6b9',
            cardBg: '#cfc6b9',
            textPrimary: '#68463c',
            textSecondary: '#87613b',
            accent: '#87613b',
            secondary: '#d0bca7',
            titleColor: '#87613b',
            specialColor: 'linear-gradient(90deg, #87613b, #68463c)',
        },
    },
    {
        id: 'trackday',
        name: 'Trackday',
        isDark: true,
        colors: {
            background: '#464d66',
            cardBg: '#464d66',
            textPrimary: '#cfcfcf',
            textSecondary: '#829cc9',
            accent: '#e87d6e',
            secondary: '#3d4359',
            titleColor: '#e87d6e',
            specialColor: 'linear-gradient(90deg, #e87d6e, #8c9bc0)',
        },
    },
    {
        id: 'trance',
        name: 'Trance',
        isDark: true,
        colors: {
            background: '#00021b',
            cardBg: '#00021b',
            textPrimary: '#ffffff',
            textSecondary: '#556cab',
            accent: '#e51376',
            secondary: '#18214c',
            titleColor: '#e51376',
            specialColor: 'linear-gradient(90deg, #e51376, #ffffff)',
        },
    },
    {
        id: 'tron-orange',
        name: 'Tron Orange',
        isDark: true,
        colors: {
            background: '#0d1c1c',
            cardBg: '#0d1c1c',
            textPrimary: '#ffffff',
            textSecondary: '#fffdfb',
            accent: '#fffeeb',
            secondary: '#9c9191',
            titleColor: '#fffeeb',
            specialColor: 'linear-gradient(90deg, #fffeeb, #ffffff)',
        },
    },
    {
        id: 'vaporwave',
        name: 'Vaporwave',
        isDark: false,
        colors: {
            background: '#a4a7ea',
            cardBg: '#a4a7ea',
            textPrimary: '#453145',
            textSecondary: '#4b4e7b',
            accent: '#8f1b87',
            secondary: '#989bd9',
            titleColor: '#8f1b87',
            specialColor: 'linear-gradient(90deg, #8f1b87, #015875)',
        },
    },
    {
        id: 'vesper',
        name: 'Vesper',
        isDark: true,
        colors: {
            background: '#101010',
            cardBg: '#101010',
            textPrimary: '#ffffff',
            textSecondary: '#a0a0a0',
            accent: '#ffc799',
            secondary: '#1c1c1c',
            titleColor: '#ffc799',
            specialColor: 'linear-gradient(90deg, #ffc799, #99ffe4)',
        },
    },
    {
        id: 'vesper-light',
        name: 'Vesper Light',
        isDark: false,
        colors: {
            background: '#ffffff',
            cardBg: '#ffffff',
            textPrimary: '#000000',
            textSecondary: '#909090',
            accent: '#ec6a00',
            secondary: '#fff8f4',
            titleColor: '#ec6a00',
            specialColor: 'linear-gradient(90deg, #ec6a00, #067a6e)',
        },
    },
    {
        id: 'viridescent',
        name: 'Viridescent',
        isDark: true,
        colors: {
            background: '#2c3333',
            cardBg: '#2c3333',
            textPrimary: '#e9f5db',
            textSecondary: '#84a98c',
            accent: '#95d5b2',
            secondary: '#232828',
            titleColor: '#95d5b2',
            specialColor: 'linear-gradient(90deg, #95d5b2, #f0d3c9)',
        },
    },
    {
        id: 'voc',
        name: 'Voc',
        isDark: true,
        colors: {
            background: '#190618',
            cardBg: '#190618',
            textPrimary: '#eeeae4',
            textSecondary: '#9e3e95',
            accent: '#e0caac',
            secondary: '#2c0c28',
            titleColor: '#e0caac',
            specialColor: 'linear-gradient(90deg, #e0caac, #eeeae4)',
        },
    },
    {
        id: 'vscode',
        name: 'VSCode',
        isDark: true,
        colors: {
            background: '#1e1e1e',
            cardBg: '#1e1e1e',
            textPrimary: '#d4d4d4',
            textSecondary: '#696969',
            accent: '#007acc',
            secondary: '#191919',
            titleColor: '#007acc',
            specialColor: 'linear-gradient(90deg, #007acc, #569cd6)',
        },
    },
    {
        id: 'watermelon',
        name: 'Watermelon',
        isDark: true,
        colors: {
            background: '#1f4437',
            cardBg: '#1f4437',
            textPrimary: '#cdc6bc',
            textSecondary: '#519f83',
            accent: '#d97278',
            secondary: '#244d3f',
            titleColor: '#d97278',
            specialColor: 'linear-gradient(90deg, #d97278, #cdc6bc)',
        },
    },
    {
        id: 'wavez',
        name: 'Wavez',
        isDark: true,
        colors: {
            background: '#1c292f',
            cardBg: '#1c292f',
            textPrimary: '#e9efe6',
            textSecondary: '#2b8293',
            accent: '#6bde3b',
            secondary: '#1b3238',
            titleColor: '#6bde3b',
            specialColor: 'linear-gradient(90deg, #6bde3b, #e9efe6)',
        },
    },
    {
        id: 'witch-girl',
        name: 'Witch Girl',
        isDark: false,
        colors: {
            background: '#f3dbda',
            cardBg: '#f3dbda',
            textPrimary: '#445e53',
            textSecondary: '#ae5d43',
            accent: '#56786a',
            secondary: '#e7c8be',
            titleColor: '#56786a',
            specialColor: 'linear-gradient(90deg, #56786a, #ae5d43)',
        },
    },
];

export function getThemeById(id: string): Theme | undefined {
    return themes.find(theme => theme.id === id);
}

export function getDefaultTheme(): Theme {
    return themes[0];
}
