import type { WeatherModel, WeatherVariable } from '../types/openMeteo';
import type { VariableConfig, ModelConfig } from '../types/detailView';
import { modelProviders } from '../data/modelHierarchy';

// Chart display settings for every Forecast model, derived from the catalogue
export const MODEL_CONFIGS: Map<WeatherModel, ModelConfig> = new Map(
  modelProviders.flatMap((provider) =>
    provider.models.map((model) => [
      model.id,
      { id: model.id, name: model.label, color: model.color, description: model.description },
    ] as const)
  )
);

// Helper to convert temperature from Celsius
const tempToImperial = (c: number): number => (c * 9) / 5 + 32;

// Helper to convert mm to inches
const mmToInches = (mm: number): number => mm / 25.4;

// Helper to convert cm to inches
const cmToInches = (cm: number): number => cm / 2.54;

// Helper to convert km/h to mph
const kmhToMph = (kmh: number): number => kmh / 1.609344;

// Helper to convert meters to feet
const mToFt = (m: number): number => m * 3.28084;

// Helper to convert hPa to inHg
const hpaToInHg = (hpa: number): number => hpa * 0.02953;

// Helper to convert kPa to psi
const kpaToPsi = (kpa: number): number => kpa * 0.145038;

// Helper to convert seconds to minutes
const secToMin = (sec: number): number => sec / 60;

// ECMWF precipitation type codes
const PRECIPITATION_TYPES: Record<number, string> = {
  0: 'None',
  1: 'Rain',
  3: 'Freezing rain',
  5: 'Snow',
  6: 'Wet snow',
  7: 'Rain and snow',
  8: 'Ice pellets',
  12: 'Freezing drizzle',
};

// Variable configurations
export const VARIABLE_CONFIGS: Map<WeatherVariable, VariableConfig> = new Map([
  ['temperature_2m', {
    id: 'temperature_2m',
    label: 'Temperature',
    unit: 'C',
    unitImperial: 'F',
    color: '#ef4444',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Air temperature at 2 meters above ground',
  }],
  ['apparent_temperature', {
    id: 'apparent_temperature',
    label: 'Feels Like',
    unit: 'C',
    unitImperial: 'F',
    color: '#f97316',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Perceived temperature combining wind chill, humidity and solar radiation',
  }],
  ['precipitation', {
    id: 'precipitation',
    label: 'Precipitation',
    unit: 'mm',
    unitImperial: 'in',
    color: '#3b82f6',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}mm` : `${mmToInches(v).toFixed(2)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Total precipitation (rain, showers, snow) sum of the preceding hour',
  }],
  ['rain', {
    id: 'rain',
    label: 'Rain',
    unit: 'mm',
    unitImperial: 'in',
    color: '#0ea5e9',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}mm` : `${mmToInches(v).toFixed(2)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Rain from large scale weather systems of the preceding hour',
  }],
  ['snowfall', {
    id: 'snowfall',
    label: 'Snowfall',
    unit: 'cm',
    unitImperial: 'in',
    color: '#06b6d4',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}cm` : `${cmToInches(v).toFixed(1)}in`,
    convertToImperial: cmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Snowfall amount of the preceding hour',
  }],
  ['snow_depth', {
    id: 'snow_depth',
    label: 'Snow Depth',
    unit: 'm',
    unitImperial: 'ft',
    color: '#22d3ee',
    chartType: 'area',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(2)}m` : `${mToFt(v).toFixed(1)}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Snow depth on the ground',
  }],
  ['snowfall_height', {
    id: 'snowfall_height',
    label: 'Snowfall Height',
    unit: 'm',
    unitImperial: 'ft',
    color: '#67e8f9',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    description: 'Height above sea level where snow turns to rain. ICON, MeteoSwiss, GeoSphere, ICON-2I and NOAA NBM only',
  }],
  ['snowfall_water_equivalent', {
    id: 'snowfall_water_equivalent',
    label: 'Snowfall Water Equivalent',
    unit: 'mm',
    unitImperial: 'in',
    color: '#0891b2',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}mm` : `${mmToInches(v).toFixed(2)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Water content of the snow that fell in the preceding hour',
  }],
  ['snow_depth_water_equivalent', {
    id: 'snow_depth_water_equivalent',
    label: 'Snowpack Water Equivalent',
    unit: 'mm',
    unitImperial: 'in',
    color: '#155e75',
    chartType: 'area',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}mm` : `${mmToInches(v).toFixed(1)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Water content of the snow on the ground',
  }],
  ['snow_density', {
    id: 'snow_density',
    label: 'Snow Density',
    unit: 'kg/m³',
    unitImperial: 'kg/m³',
    color: '#a5f3fc',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}kg/m³`,
    yAxisDomain: [0, 'auto'],
    description: 'Density of the snow on the ground; fresh powder is light, old snow is dense',
  }],
  ['precipitation_type', {
    id: 'precipitation_type',
    label: 'Precipitation Type',
    unit: '',
    unitImperial: '',
    color: '#7dd3fc',
    chartType: 'line',
    formatValue: (v) => PRECIPITATION_TYPES[Math.round(v)] ?? `${Math.round(v)}`,
    yAxisDomain: [0, 12],
    description: 'ECMWF code: 1 rain, 3 freezing rain, 5 snow, 6 wet snow, 7 rain and snow, 8 ice pellets. ECMWF IFS 0.25°, CMA and the ECMWF-backed Seamless models only',
  }],
  ['hail', {
    id: 'hail',
    label: 'Hail',
    unit: 'mm',
    unitImperial: 'in',
    color: '#e2e8f0',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}mm` : `${mmToInches(v).toFixed(2)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Hail of the preceding hour. UK Met Office UK model only',
  }],
  ['lightning_potential', {
    id: 'lightning_potential',
    label: 'Lightning Potential',
    unit: 'J/kg',
    unitImperial: 'J/kg',
    color: '#facc15',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}J/kg`,
    yAxisDomain: [0, 'auto'],
    description: 'Lightning Potential Index. ICON-D2 and ICON-2I only',
  }],
  ['thunderstorm_probability', {
    id: 'thunderstorm_probability',
    label: 'Thunderstorm Probability',
    unit: '%',
    unitImperial: '%',
    color: '#eab308',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Chance of a thunderstorm. NOAA NBM (US) only',
  }],
  ['snowfall_probability', {
    id: 'snowfall_probability',
    label: 'Snowfall Probability',
    unit: '%',
    unitImperial: '%',
    color: '#38bdf8',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Chance of snowfall. NOAA NBM (US) only',
  }],
  ['freezing_rain_probability', {
    id: 'freezing_rain_probability',
    label: 'Freezing Rain Probability',
    unit: '%',
    unitImperial: '%',
    color: '#818cf8',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Chance of freezing rain. NOAA NBM (US) only',
  }],
  ['ice_pellets_probability', {
    id: 'ice_pellets_probability',
    label: 'Ice Pellets Probability',
    unit: '%',
    unitImperial: '%',
    color: '#94a3b8',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Chance of ice pellets. NOAA NBM (US) only',
  }],
  ['rain_probability', {
    id: 'rain_probability',
    label: 'Rain Probability',
    unit: '%',
    unitImperial: '%',
    color: '#3b82f6',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Chance of rain. NOAA NBM (US) only',
  }],
  ['wind_speed_10m', {
    id: 'wind_speed_10m',
    label: 'Wind Speed',
    unit: 'km/h',
    unitImperial: 'mph',
    color: '#84cc16',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}km/h` : `${Math.round(kmhToMph(v))}mph`,
    convertToImperial: kmhToMph,
    yAxisDomain: [0, 'auto'],
    description: 'Wind speed at 10 meters above ground',
  }],
  ['wind_gusts_10m', {
    id: 'wind_gusts_10m',
    label: 'Wind Gusts',
    unit: 'km/h',
    unitImperial: 'mph',
    color: '#eab308',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}km/h` : `${Math.round(kmhToMph(v))}mph`,
    convertToImperial: kmhToMph,
    yAxisDomain: [0, 'auto'],
    description: 'Maximum wind gusts of the preceding hour at 10m above ground',
  }],
  ['wind_direction_10m', {
    id: 'wind_direction_10m',
    label: 'Wind Direction',
    unit: '',
    unitImperial: '',
    color: '#a3e635',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    yAxisDomain: [0, 360],
    description: 'Wind direction at 10 meters above ground',
  }],
  ['relative_humidity_2m', {
    id: 'relative_humidity_2m',
    label: 'Humidity',
    unit: '%',
    unitImperial: '%',
    color: '#a78bfa',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Relative humidity at 2 meters above ground',
  }],
  ['surface_pressure', {
    id: 'surface_pressure',
    label: 'Pressure',
    unit: 'hPa',
    unitImperial: 'inHg',
    color: '#c084fc',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}hPa` : `${hpaToInHg(v).toFixed(2)}inHg`,
    convertToImperial: hpaToInHg,
    description: 'Atmospheric air pressure at surface',
  }],
  ['cloud_cover', {
    id: 'cloud_cover',
    label: 'Cloud Cover',
    unit: '%',
    unitImperial: '%',
    color: '#94a3b8',
    chartType: 'line', // Changed from area to line for better multi-model comparison
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Total cloud cover as an area fraction',
    defaultHeight: 200,
  }],
  ['cloud_cover_low', {
    id: 'cloud_cover_low',
    label: 'Low Clouds',
    unit: '%',
    unitImperial: '%',
    color: '#cbd5e1',
    chartType: 'line', // Changed from area to line for better multi-model comparison
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Low level clouds and fog up to 3 km altitude',
    defaultHeight: 200,
  }],
  ['cloud_cover_mid', {
    id: 'cloud_cover_mid',
    label: 'Mid Clouds',
    unit: '%',
    unitImperial: '%',
    color: '#9ca3af',
    chartType: 'line', // Changed from area to line for better multi-model comparison
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Mid level clouds from 3 to 8 km altitude',
    defaultHeight: 200,
  }],
  ['cloud_cover_high', {
    id: 'cloud_cover_high',
    label: 'High Clouds',
    unit: '%',
    unitImperial: '%',
    color: '#6b7280',
    chartType: 'line', // Changed from area to line for better multi-model comparison
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'High level clouds from 8 km altitude',
    defaultHeight: 200,
  }],
  ['visibility', {
    id: 'visibility',
    label: 'Visibility',
    unit: 'm',
    unitImperial: 'ft',
    color: '#fbbf24',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${(v / 1000).toFixed(1)}km` : `${(mToFt(v) / 5280).toFixed(1)}mi`,
    convertToImperial: mToFt,
    description: 'Viewing distance influenced by clouds, humidity and aerosols',
  }],
  ['cloud_cover_2m', {
    id: 'cloud_cover_2m',
    label: 'Fog',
    unit: '%',
    unitImperial: '%',
    color: '#e5e7eb',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Cloud cover at 2 m above ground, i.e. fog. Few models provide it',
    defaultHeight: 200,
  }],
  ['cloud_base', {
    id: 'cloud_base',
    label: 'Cloud Base',
    unit: 'm',
    unitImperial: 'ft',
    color: '#cbd5e1',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Height of the lowest cloud base. DMI and MeteoSwiss only',
  }],
  ['cloud_top', {
    id: 'cloud_top',
    label: 'Cloud Top',
    unit: 'm',
    unitImperial: 'ft',
    color: '#64748b',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Height of the highest cloud top. DMI only',
  }],
  ['convective_cloud_base', {
    id: 'convective_cloud_base',
    label: 'Convective Cloud Base',
    unit: 'm',
    unitImperial: 'ft',
    color: '#a8a29e',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Base of shower and thunderstorm clouds',
  }],
  ['convective_cloud_top', {
    id: 'convective_cloud_top',
    label: 'Convective Cloud Top',
    unit: 'm',
    unitImperial: 'ft',
    color: '#78716c',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Top of shower and thunderstorm clouds',
  }],
  ['freezing_level_height', {
    id: 'freezing_level_height',
    label: 'Freezing Level',
    unit: 'm',
    unitImperial: 'ft',
    color: '#2dd4bf',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    description: 'Altitude above sea level of the 0°C level',
  }],
  ['weather_code', {
    id: 'weather_code',
    label: 'Weather Code',
    unit: '',
    unitImperial: '',
    color: '#f472b6',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    yAxisDomain: [0, 100],
    description: 'Weather condition as a numeric WMO code',
  }],
  // New variables
  ['dew_point_2m', {
    id: 'dew_point_2m',
    label: 'Dew Point',
    unit: 'C',
    unitImperial: 'F',
    color: '#14b8a6',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Dew point temperature at 2 meters above ground',
  }],
  ['wet_bulb_temperature_2m', {
    id: 'wet_bulb_temperature_2m',
    label: 'Wet Bulb Temp',
    unit: 'C',
    unitImperial: 'F',
    color: '#0d9488',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature accounting for evaporative cooling; indicates snow quality',
  }],
  ['precipitation_probability', {
    id: 'precipitation_probability',
    label: 'Precip Probability',
    unit: '%',
    unitImperial: '%',
    color: '#6366f1',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}%`,
    yAxisDomain: [0, 100],
    description: 'Probability of precipitation with more than 0.1 mm',
  }],
  ['showers', {
    id: 'showers',
    label: 'Showers',
    unit: 'mm',
    unitImperial: 'in',
    color: '#818cf8',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(1)}mm` : `${mmToInches(v).toFixed(2)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Showers from convective precipitation',
  }],
  ['pressure_msl', {
    id: 'pressure_msl',
    label: 'Sea Level Pressure',
    unit: 'hPa',
    unitImperial: 'inHg',
    color: '#a855f7',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}hPa` : `${hpaToInHg(v).toFixed(2)}inHg`,
    convertToImperial: hpaToInHg,
    description: 'Atmospheric air pressure reduced to mean sea level',
  }],
  ['vapour_pressure_deficit', {
    id: 'vapour_pressure_deficit',
    label: 'Vapour Pressure Deficit',
    unit: 'kPa',
    unitImperial: 'psi',
    color: '#d946ef',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(2)}kPa` : `${kpaToPsi(v).toFixed(3)}psi`,
    convertToImperial: kpaToPsi,
    yAxisDomain: [0, 'auto'],
    description: 'VPD affects plant water transpiration; high >1.6, low <0.4 kPa',
  }],
  ['boundary_layer_height', {
    id: 'boundary_layer_height',
    label: 'Boundary Layer Height',
    unit: 'm',
    unitImperial: 'ft',
    color: '#7c3aed',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}m` : `${Math.round(mToFt(v))}ft`,
    convertToImperial: mToFt,
    yAxisDomain: [0, 'auto'],
    description: 'Height of the atmospheric boundary layer',
  }],
  ['shortwave_radiation', {
    id: 'shortwave_radiation',
    label: 'Shortwave Radiation',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#fbbf24',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Total global horizontal solar irradiation',
  }],
  ['direct_radiation', {
    id: 'direct_radiation',
    label: 'Direct Radiation',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#f59e0b',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Direct solar radiation on the horizontal plane',
  }],
  ['diffuse_radiation', {
    id: 'diffuse_radiation',
    label: 'Diffuse Radiation',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#d97706',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Diffuse solar radiation (scattered by atmosphere)',
  }],
  ['direct_normal_irradiance', {
    id: 'direct_normal_irradiance',
    label: 'Direct Normal Irradiance',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#ea580c',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Direct solar radiation perpendicular to the sun',
  }],
  ['global_tilted_irradiance', {
    id: 'global_tilted_irradiance',
    label: 'Global Tilted Irradiance',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#c2410c',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Total radiation received on a tilted surface',
  }],
  ['terrestrial_radiation', {
    id: 'terrestrial_radiation',
    label: 'Terrestrial Radiation',
    unit: 'W/m²',
    unitImperial: 'W/m²',
    color: '#9a3412',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}W/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'Longwave radiation emitted by Earth surface',
  }],
  ['uv_index', {
    id: 'uv_index',
    label: 'UV Index',
    unit: '',
    unitImperial: '',
    color: '#e11d48',
    chartType: 'line',
    formatValue: (v) => `${v.toFixed(1)}`,
    yAxisDomain: [0, 12],
    description: 'UV radiation intensity index',
  }],
  ['uv_index_clear_sky', {
    id: 'uv_index_clear_sky',
    label: 'UV Index (Clear Sky)',
    unit: '',
    unitImperial: '',
    color: '#be123c',
    chartType: 'line',
    formatValue: (v) => `${v.toFixed(1)}`,
    yAxisDomain: [0, 12],
    description: 'UV index assuming clear sky conditions',
  }],
  ['sunshine_duration', {
    id: 'sunshine_duration',
    label: 'Sunshine Duration',
    unit: 'sec',
    unitImperial: 'min',
    color: '#facc15',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}s` : `${secToMin(v).toFixed(1)}min`,
    convertToImperial: secToMin,
    yAxisDomain: [0, 'auto'],
    description: 'Duration of direct sunlight per hour',
  }],
  ['is_day', {
    id: 'is_day',
    label: 'Day/Night',
    unit: '',
    unitImperial: '',
    color: '#fde047',
    chartType: 'area',
    formatValue: (v) => v === 1 ? 'Day' : 'Night',
    yAxisDomain: [0, 1],
    description: '1 if daylight, 0 at night',
  }],
  ['soil_temperature_0cm', {
    id: 'soil_temperature_0cm',
    label: 'Soil Temperature',
    unit: 'C',
    unitImperial: 'F',
    color: '#a16207',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature at the soil/water surface',
  }],
  ['soil_moisture_0_to_1cm', {
    id: 'soil_moisture_0_to_1cm',
    label: 'Soil Moisture',
    unit: 'm³/m³',
    unitImperial: 'm³/m³',
    color: '#854d0e',
    chartType: 'area',
    formatValue: (v) => `${v.toFixed(3)}`,
    yAxisDomain: [0, 1],
    description: 'Average soil water content at 0-1 cm depth',
  }],
  ['evapotranspiration', {
    id: 'evapotranspiration',
    label: 'Evapotranspiration',
    unit: 'mm',
    unitImperial: 'in',
    color: '#65a30d',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(2)}mm` : `${mmToInches(v).toFixed(3)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'Water loss from land surface and plants',
  }],
  ['et0_fao_evapotranspiration', {
    id: 'et0_fao_evapotranspiration',
    label: 'Reference Evapotranspiration',
    unit: 'mm',
    unitImperial: 'in',
    color: '#4d7c0f',
    chartType: 'bar',
    formatValue: (v, u) => u === 'metric' ? `${v.toFixed(2)}mm` : `${mmToInches(v).toFixed(3)}in`,
    convertToImperial: mmToInches,
    yAxisDomain: [0, 'auto'],
    description: 'ET₀ reference for well-watered grass (FAO-56)',
  }],
  ['cape', {
    id: 'cape',
    label: 'CAPE',
    unit: 'J/kg',
    unitImperial: 'J/kg',
    color: '#dc2626',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}J/kg`,
    yAxisDomain: [0, 'auto'],
    description: 'Convective Available Potential Energy; storm indicator',
  }],
  ['lifted_index', {
    id: 'lifted_index',
    label: 'Lifted Index',
    unit: '',
    unitImperial: '',
    color: '#b91c1c',
    chartType: 'line',
    formatValue: (v) => `${v.toFixed(1)}`,
    description: 'Atmospheric stability index; negative = unstable',
  }],
  ['convective_inhibition', {
    id: 'convective_inhibition',
    label: 'Convective Inhibition',
    unit: 'J/kg',
    unitImperial: 'J/kg',
    color: '#991b1b',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}J/kg`,
    yAxisDomain: ['auto', 0],
    description: 'Energy needed to overcome and trigger convection',
  }],
  ['k_index', {
    id: 'k_index',
    label: 'K-Index',
    unit: '',
    unitImperial: '',
    color: '#f87171',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    description: 'Thunderstorm potential; above 30 is high. Few models provide it',
  }],
  ['updraft', {
    id: 'updraft',
    label: 'Updraft',
    unit: 'm/s',
    unitImperial: 'm/s',
    color: '#fb923c',
    chartType: 'line',
    formatValue: (v) => `${v.toFixed(1)}m/s`,
    yAxisDomain: [0, 'auto'],
    description: 'Strongest upward wind in the atmospheric column. ICON models only',
  }],
  ['total_column_integrated_water_vapour', {
    id: 'total_column_integrated_water_vapour',
    label: 'Water Vapour Column',
    unit: 'kg/m²',
    unitImperial: 'kg/m²',
    color: '#2563eb',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}kg/m²`,
    yAxisDomain: [0, 'auto'],
    description: 'All the water vapour above this point; high values mark atmospheric rivers',
  }],
  ['surface_temperature', {
    id: 'surface_temperature',
    label: 'Surface Temperature',
    unit: 'C',
    unitImperial: 'F',
    color: '#fca5a5',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature of the snow or ground surface',
  }],
  ['skin_temperature', {
    id: 'skin_temperature',
    label: 'Skin Temperature',
    unit: 'C',
    unitImperial: 'F',
    color: '#fecaca',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Radiating temperature of the snow or ground surface; below air temperature on clear nights',
  }],
  // Temperature aloft (80m base with 120m and 180m overlays). A separate chart rather than
  // overlays on temperature_2m, so the default variables don't cost extra calls.
  ['temperature_80m', {
    id: 'temperature_80m',
    label: 'Temperature Aloft',
    unit: 'C',
    unitImperial: 'F',
    color: '#f43f5e',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Air temperature at 80 meters above ground, with 120 m and 180 m overlays',
  }],
  ['temperature_120m', {
    id: 'temperature_120m',
    label: 'Temperature (120m)',
    unit: 'C',
    unitImperial: 'F',
    color: '#e11d48',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Air temperature at 120 meters above ground',
  }],
  ['temperature_180m', {
    id: 'temperature_180m',
    label: 'Temperature (180m)',
    unit: 'C',
    unitImperial: 'F',
    color: '#be123c',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Air temperature at 180 meters above ground',
  }],
  // Wind speed overlay levels
  ['wind_speed_80m', {
    id: 'wind_speed_80m',
    label: 'Wind Speed (80m)',
    unit: 'km/h',
    unitImperial: 'mph',
    color: '#22c55e',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}km/h` : `${Math.round(kmhToMph(v))}mph`,
    convertToImperial: kmhToMph,
    yAxisDomain: [0, 'auto'],
    description: 'Wind speed at 80 meters above ground',
  }],
  ['wind_speed_120m', {
    id: 'wind_speed_120m',
    label: 'Wind Speed (120m)',
    unit: 'km/h',
    unitImperial: 'mph',
    color: '#16a34a',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}km/h` : `${Math.round(kmhToMph(v))}mph`,
    convertToImperial: kmhToMph,
    yAxisDomain: [0, 'auto'],
    description: 'Wind speed at 120 meters above ground',
  }],
  ['wind_speed_180m', {
    id: 'wind_speed_180m',
    label: 'Wind Speed (180m)',
    unit: 'km/h',
    unitImperial: 'mph',
    color: '#15803d',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}km/h` : `${Math.round(kmhToMph(v))}mph`,
    convertToImperial: kmhToMph,
    yAxisDomain: [0, 'auto'],
    description: 'Wind speed at 180 meters above ground',
  }],
  // Wind direction overlay levels
  ['wind_direction_80m', {
    id: 'wind_direction_80m',
    label: 'Wind Direction (80m)',
    unit: '',
    unitImperial: '',
    color: '#4ade80',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    yAxisDomain: [0, 360],
    description: 'Wind direction at 80 meters above ground',
  }],
  ['wind_direction_120m', {
    id: 'wind_direction_120m',
    label: 'Wind Direction (120m)',
    unit: '',
    unitImperial: '',
    color: '#22c55e',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    yAxisDomain: [0, 360],
    description: 'Wind direction at 120 meters above ground',
  }],
  ['wind_direction_180m', {
    id: 'wind_direction_180m',
    label: 'Wind Direction (180m)',
    unit: '',
    unitImperial: '',
    color: '#16a34a',
    chartType: 'line',
    formatValue: (v) => `${Math.round(v)}`,
    yAxisDomain: [0, 360],
    description: 'Wind direction at 180 meters above ground',
  }],
  // Soil temperature overlay levels
  ['soil_temperature_6cm', {
    id: 'soil_temperature_6cm',
    label: 'Soil Temp (6cm)',
    unit: 'C',
    unitImperial: 'F',
    color: '#ca8a04',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature at 6cm soil depth',
  }],
  ['soil_temperature_18cm', {
    id: 'soil_temperature_18cm',
    label: 'Soil Temp (18cm)',
    unit: 'C',
    unitImperial: 'F',
    color: '#a16207',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature at 18cm soil depth',
  }],
  ['soil_temperature_54cm', {
    id: 'soil_temperature_54cm',
    label: 'Soil Temp (54cm)',
    unit: 'C',
    unitImperial: 'F',
    color: '#854d0e',
    chartType: 'line',
    formatValue: (v, u) => u === 'metric' ? `${Math.round(v)}C` : `${Math.round(tempToImperial(v))}F`,
    convertToImperial: tempToImperial,
    description: 'Temperature at 54cm soil depth',
  }],
  // Soil moisture overlay levels
  ['soil_moisture_1_to_3cm', {
    id: 'soil_moisture_1_to_3cm',
    label: 'Soil Moisture (1-3cm)',
    unit: 'm³/m³',
    unitImperial: 'm³/m³',
    color: '#a16207',
    chartType: 'area',
    formatValue: (v) => `${v.toFixed(3)}`,
    yAxisDomain: [0, 1],
    description: 'Average soil water content at 1-3cm depth',
  }],
  ['soil_moisture_3_to_9cm', {
    id: 'soil_moisture_3_to_9cm',
    label: 'Soil Moisture (3-9cm)',
    unit: 'm³/m³',
    unitImperial: 'm³/m³',
    color: '#92400e',
    chartType: 'area',
    formatValue: (v) => `${v.toFixed(3)}`,
    yAxisDomain: [0, 1],
    description: 'Average soil water content at 3-9cm depth',
  }],
  ['soil_moisture_9_to_27cm', {
    id: 'soil_moisture_9_to_27cm',
    label: 'Soil Moisture (9-27cm)',
    unit: 'm³/m³',
    unitImperial: 'm³/m³',
    color: '#78350f',
    chartType: 'area',
    formatValue: (v) => `${v.toFixed(3)}`,
    yAxisDomain: [0, 1],
    description: 'Average soil water content at 9-27cm depth',
  }],
  ['soil_moisture_27_to_81cm', {
    id: 'soil_moisture_27_to_81cm',
    label: 'Soil Moisture (27-81cm)',
    unit: 'm³/m³',
    unitImperial: 'm³/m³',
    color: '#713f12',
    chartType: 'area',
    formatValue: (v) => `${v.toFixed(3)}`,
    yAxisDomain: [0, 1],
    description: 'Average soil water content at 27-81cm depth',
  }],
]);

// Default selected models - all seamless models
export const DEFAULT_MODELS: WeatherModel[] = [
  'icon_seamless',
  'gfs_seamless',
  'gem_seamless',
  'meteofrance_seamless',
  'metno_seamless',
  'knmi_seamless',
  'jma_seamless',
  'ukmo_seamless',
  'dmi_seamless',
  'meteoswiss_icon_seamless',
  'kma_seamless',
];

// Default selected variables
export const DEFAULT_VARIABLES: WeatherVariable[] = [
  'temperature_2m',
  'precipitation',
  'snowfall',
  'wind_speed_10m',
  'relative_humidity_2m',
  'cloud_cover',
  'freezing_level_height',
];

// All available variables (in display order)
export const ALL_VARIABLES: WeatherVariable[] = [
  // Temperature
  'temperature_2m',
  'apparent_temperature',
  'dew_point_2m',
  'wet_bulb_temperature_2m',
  // Precipitation
  'precipitation',
  'precipitation_probability',
  'rain',
  'showers',
  'snowfall',
  'snow_depth',
  // Wind
  'wind_speed_10m',
  'wind_gusts_10m',
  'wind_direction_10m',
  // Atmosphere
  'relative_humidity_2m',
  'surface_pressure',
  'pressure_msl',
  'vapour_pressure_deficit',
  'boundary_layer_height',
  // Clouds & Visibility
  'cloud_cover',
  'cloud_cover_low',
  'cloud_cover_mid',
  'cloud_cover_high',
  'visibility',
  // Solar & Radiation
  'shortwave_radiation',
  'direct_radiation',
  'diffuse_radiation',
  'direct_normal_irradiance',
  'global_tilted_irradiance',
  'terrestrial_radiation',
  // UV & Sunshine
  'uv_index',
  'uv_index_clear_sky',
  'sunshine_duration',
  'is_day',
  // Soil
  'soil_temperature_0cm',
  'soil_moisture_0_to_1cm',
  'evapotranspiration',
  'et0_fao_evapotranspiration',
  // Convective/Stability
  'cape',
  'lifted_index',
  'convective_inhibition',
  'freezing_level_height',
  'weather_code',
];

// All available models (in display order)
export const ALL_MODELS: WeatherModel[] = [
  'best_match',
  // ECMWF
  'ecmwf_ifs',
  'ecmwf_ifs025',
  'ecmwf_aifs025_single',
  // ICON
  'icon_seamless',
  'icon_global',
  'icon_eu',
  'icon_d2',
  // GFS
  'gfs_seamless',
  'gfs_global',
  'gfs_hrrr',
  'gfs_graphcast025',
  // GEM
  'gem_seamless',
  'gem_global',
  'gem_regional',
  'gem_hrdps_continental',
  'gem_hrdps_west',
  // Meteo-France
  'meteofrance_seamless',
  'meteofrance_arpege_world',
  'meteofrance_arpege_europe',
  'meteofrance_arome_france',
  'meteofrance_arome_france_hd',
  // MetNo
  'metno_seamless',
  'metno_nordic',
  // KNMI
  'knmi_seamless',
  'knmi_harmonie_arome_europe',
  'knmi_harmonie_arome_netherlands',
  // JMA
  'jma_seamless',
  'jma_msm',
  'jma_gsm',
  // UKMO
  'ukmo_seamless',
  'ukmo_global_deterministic_10km',
  'ukmo_uk_deterministic_2km',
  // DMI
  'dmi_seamless',
  'dmi_harmonie_arome_europe',
  // MeteoSwiss
  'meteoswiss_icon_seamless',
  'meteoswiss_icon_ch1',
  'meteoswiss_icon_ch2',
  // KMA
  'kma_seamless',
  'kma_gdps',
  'kma_ldps',
  // Other
  'cma_grapes_global',
  'bom_access_global',
  'ncep_nbm_conus',
  'ncep_nam_conus',
  'italia_meteo_arpae_icon_2i',
];

// Get model config with fallback
export function getModelConfig(modelId: WeatherModel): ModelConfig {
  return MODEL_CONFIGS.get(modelId) ?? {
    id: modelId,
    name: modelId,
    color: '#6b7280',
  };
}

// Get variable config with fallback
export function getVariableConfig(variableId: WeatherVariable): VariableConfig {
  return VARIABLE_CONFIGS.get(variableId) ?? {
    id: variableId,
    label: variableId,
    unit: '',
    unitImperial: '',
    color: '#6b7280',
    chartType: 'line',
    formatValue: (v) => `${Number.isInteger(v) ? v : parseFloat(v.toFixed(2))}`,
  };
}

// Overlay level configuration
export interface OverlayLevel {
  variable: WeatherVariable;
  label: string;
  color: string;
  opacity?: number;
}

// Overlay configuration for a base variable
export interface OverlayConfig {
  baseVariable: WeatherVariable;
  overlays: OverlayLevel[];
  description: string;
}

// Overlay configurations - maps base variables to their overlay levels
export const OVERLAY_CONFIGS: OverlayConfig[] = [
  {
    baseVariable: 'wind_speed_10m',
    overlays: [
      { variable: 'wind_speed_80m', label: '80m', color: '#22c55e', opacity: 0.7 },
      { variable: 'wind_speed_120m', label: '120m', color: '#16a34a', opacity: 0.6 },
      { variable: 'wind_speed_180m', label: '180m', color: '#15803d', opacity: 0.5 },
    ],
    description: 'altitude levels',
  },
  {
    baseVariable: 'wind_direction_10m',
    overlays: [
      { variable: 'wind_direction_80m', label: '80m', color: '#4ade80', opacity: 0.7 },
      { variable: 'wind_direction_120m', label: '120m', color: '#22c55e', opacity: 0.6 },
      { variable: 'wind_direction_180m', label: '180m', color: '#16a34a', opacity: 0.5 },
    ],
    description: 'altitude levels',
  },
  {
    baseVariable: 'soil_temperature_0cm',
    overlays: [
      { variable: 'soil_temperature_6cm', label: '6cm', color: '#ca8a04', opacity: 0.7 },
      { variable: 'soil_temperature_18cm', label: '18cm', color: '#a16207', opacity: 0.6 },
      { variable: 'soil_temperature_54cm', label: '54cm', color: '#854d0e', opacity: 0.5 },
    ],
    description: 'depth levels',
  },
  {
    baseVariable: 'soil_moisture_0_to_1cm',
    overlays: [
      { variable: 'soil_moisture_1_to_3cm', label: '1-3cm', color: '#a16207', opacity: 0.7 },
      { variable: 'soil_moisture_3_to_9cm', label: '3-9cm', color: '#92400e', opacity: 0.6 },
      { variable: 'soil_moisture_9_to_27cm', label: '9-27cm', color: '#78350f', opacity: 0.5 },
      { variable: 'soil_moisture_27_to_81cm', label: '27-81cm', color: '#713f12', opacity: 0.4 },
    ],
    description: 'depth levels',
  },
];

// Get overlay config for a base variable
export function getOverlayConfig(baseVariable: WeatherVariable): OverlayConfig | undefined {
  return OVERLAY_CONFIGS.find(config => config.baseVariable === baseVariable);
}

// Check if a variable has overlays
export function hasOverlays(variable: WeatherVariable): boolean {
  return OVERLAY_CONFIGS.some(config => config.baseVariable === variable);
}

// Get all overlay variable names (for filtering from selection UI)
export function getAllOverlayVariables(): Set<WeatherVariable> {
  const overlayVars = new Set<WeatherVariable>();
  for (const config of OVERLAY_CONFIGS) {
    config.overlays.forEach(o => overlayVars.add(o.variable));
  }
  return overlayVars;
}

// Check if a variable is an overlay variable (not a base variable)
export function isOverlayVariable(variable: WeatherVariable): boolean {
  return getAllOverlayVariables().has(variable);
}

// Get all overlay variables for a base variable
export function getOverlayVariablesFor(baseVariable: WeatherVariable): WeatherVariable[] {
  const config = getOverlayConfig(baseVariable);
  return config ? config.overlays.map(o => o.variable) : [];
}
